const PAGES={
about:{
en:{
kicker:"About VOCE",
title:"A research and cultural house for the systems reshaping human life.",
deck:"VOCE is an independent French non-profit association. It brings together applied research, scientific and cultural mediation, public education and editorial intelligence to make contemporary systems more intelligible without flattening their complexity.",
meta:["Paris","London","Dubai","Hangzhou","Shanghai","Hong Kong"],
sections:[
["01","What VOCE is","VOCE was built around a simple conviction: the major transformations of contemporary life no longer fit inside one discipline. Artificial intelligence affects work and responsibility. Digital environments reshape attention and relationships. Medicine is transformed by data, biomarkers and software. Culture and design preserve forms of intelligence that technical analysis alone cannot explain.","VOCE therefore works as a house of inquiry rather than a conventional media brand. It studies mechanisms, architectures and human consequences, then translates that work into research papers, courses, briefings, seminars and public-facing editorial formats.","Its ambition is not to comment on everything. It is to make a smaller number of difficult subjects unusually clear."],
["02","The intellectual architecture","VOCE connects fields that are usually separated: artificial intelligence and governance, neuroscience and psychology, health and medicine, digital environments and human behaviour, education and society, culture and heritage, technology, infrastructure and work.","The common thread is the relationship between systems and human agency. What does a technology allow? What does an institution delegate? What happens to attention, judgment, expertise, memory, language, trust or responsibility when an operating system changes?","This is why a VOCE analysis can begin with a technical protocol and end with a question of apprenticeship, childhood, care, cultural transmission or institutional legitimacy."],
["03","Research before posture","VOCE does not begin with a political, commercial or technological position and search for evidence that supports it. The method begins with the object: a study, architecture, regulation, infrastructure, clinical mechanism, platform behaviour, historical object or institutional decision.","The work then separates what is documented from what is inferred, distinguishes correlation from causality, and identifies methodological limits. The result is written to remain intelligible to a non-specialist without reducing the technical substance.","Formal research outputs are distinguished from editorial analysis. VOCE Research publishes work with persistent identifiers where appropriate; VOCE’s editorial corpus interprets recent evidence and systems for a wider audience."],
["04","A scientific committee inside the ecosystems","VOCE draws on a scientific committee and expert network whose members and contributors work inside the environments being analysed. The network brings together technology practitioners, psychiatrists, cultural actors, artists, people working with foundations and institutions, and experts exposed to different regional systems.","Paris and London offer institutional, financial, cultural and research depth. Dubai provides a Gulf vantage point where infrastructure, capital and technology adoption are moving quickly. Hangzhou, Shanghai and Hong Kong offer different Chinese perspectives on platforms, commerce, industry, finance, luxury, technology and cross-border systems.","The purpose of this geography is comparative intelligence. VOCE does not treat one market as the default model for the world."],
["05","Opera, philosophy and the VOCE method","Opera is not a decorative layer of the brand. It provides a method. Several voices can occupy the same scene without becoming the same voice. Evidence, clinical experience, technical architecture, institutional practice and culture can remain distinct before being interpreted together.","Italian philosophy offers another form of discipline. Vico asks what it means to understand what we build. Machiavelli asks how agency survives inside unstable systems. Croce asks how history is made present. Leopardi asks what happens inside the human mind when the world and desire exceed it.","VOCE uses these counterpoints to resist two simplifications: treating technology as destiny, and treating the human as an abstract moral slogan."],
["06","What VOCE produces","VOCE Research develops formal and applied research. The VOCE AI Governance Institute examines model-to-system risk, agents, RAG, orchestration, sovereignty, security, observability, accountability and institutional capability. COURS VOCE® explains difficult mechanisms in a compact expert format. Editorial series connect science, medicine, technology, culture, infrastructure and human behaviour.","Seminars and institutional work deepen selected subjects with organisations, experts and cultural partners. The objective remains educational and analytical. VOCE does not provide medical care and does not replace clinical, legal or regulatory advice."],
["07","No one left unheard","The phrase predates the current expansion of VOCE, but it still defines the institution. “No one left unheard” does not mean that every claim is equivalent. It means that systems should be read with attention to the people, disciplines and consequences that are easiest to remove from the frame.","VOCE’s role is to preserve that plurality without abandoning standards of evidence. The voice matters precisely because it is confronted with facts, method and other voices."]
],
linksTitle:"Continue through VOCE",
links:[
["Research","How VOCE distinguishes formal research, applied research and editorial analysis.","/research.html"],
["Governance & Standards","How VOCE works, checks sources, handles limits, corrections and AI-assisted research.","/standards.html"],
["AI Governance","VOCE’s technical research pathway on institutional AI systems.","/governance.html"],
["Publications","Formal research outputs, DOI records and the wider editorial corpus.","/publications.html"]
]
},
fr:{
kicker:"À propos de VOCE",
title:"Une maison de recherche et de culture pour les systèmes qui transforment la vie humaine.",
deck:"VOCE est une association française indépendante à but non lucratif. Elle réunit recherche appliquée, médiation scientifique et culturelle, éducation du public et intelligence éditoriale afin de rendre les systèmes contemporains plus intelligibles sans en aplatir la complexité.",
meta:["Paris","Londres","Dubaï","Hangzhou","Shanghai","Hong Kong"],
sections:[
["01","Ce qu’est VOCE","VOCE est née d’une conviction simple: les transformations majeures de la vie contemporaine ne tiennent plus dans une seule discipline. L’intelligence artificielle transforme le travail et la responsabilité. Les environnements numériques modifient l’attention et les relations. La médecine se transforme avec les données, les biomarqueurs et le logiciel. La culture et le design conservent des formes d’intelligence que l’analyse technique seule ne suffit pas à expliquer.","VOCE fonctionne donc comme une maison d’enquête plutôt que comme un média conventionnel. Elle étudie des mécanismes, des architectures et leurs conséquences humaines, puis transforme ce travail en recherches, cours, notes, séminaires et formats éditoriaux ouverts au public.","Son ambition n’est pas de commenter tout. Elle consiste à rendre un nombre plus limité de sujets difficiles exceptionnellement clairs."],
["02","L’architecture intellectuelle","VOCE relie des domaines habituellement séparés: intelligence artificielle et gouvernance, neurosciences et psychologie, santé et médecine, environnements numériques et comportement humain, éducation et société, culture et patrimoine, technologie, infrastructures et travail.","Le fil commun est la relation entre les systèmes et l’agentivité humaine. Que permet une technologie? Que délègue une institution? Que deviennent attention, jugement, expertise, mémoire, langage, confiance ou responsabilité lorsqu’un système opérationnel change?","C’est pourquoi une analyse VOCE peut commencer par un protocole technique et finir par une question d’apprentissage, d’enfance, de soin, de transmission culturelle ou de légitimité institutionnelle."],
["03","La recherche avant la posture","VOCE ne part pas d’une position politique, commerciale ou technologique pour chercher ensuite les éléments qui la confirment. La méthode part de l’objet: étude, architecture, réglementation, infrastructure, mécanisme clinique, comportement de plateforme, objet historique ou décision institutionnelle.","Le travail sépare ensuite ce qui est documenté de ce qui est inféré, distingue corrélation et causalité et rend visibles les limites méthodologiques. L’écriture doit rester intelligible à un non-spécialiste sans réduire la substance technique.","Les travaux de recherche formels sont distingués de l’analyse éditoriale. VOCE Research publie, lorsque cela est pertinent, avec identifiants persistants; le corpus éditorial VOCE interprète les données et les systèmes récents pour un public plus large."],
["04","Un comité scientifique au contact des écosystèmes","VOCE s’appuie sur un comité scientifique et un réseau d’experts dont les membres et contributeurs travaillent au sein des environnements étudiés. Le réseau croise praticiens de la technologie, psychiatres, acteurs culturels, artistes, personnes engagées auprès de fondations et d’institutions, ainsi que des experts exposés à des systèmes régionaux différents.","Paris et Londres apportent profondeur institutionnelle, financière, culturelle et scientifique. Dubaï offre un point d’observation du Golfe où infrastructures, capital et adoption technologique avancent rapidement. Hangzhou, Shanghai et Hong Kong donnent accès à des perspectives chinoises distinctes sur plateformes, commerce, industrie, finance, luxe, technologie et systèmes transfrontaliers.","Cette géographie sert une intelligence comparative. VOCE ne prend pas un seul marché pour modèle par défaut du monde."],
["05","L’opéra, la philosophie et la méthode VOCE","L’opéra n’est pas une couche décorative de la marque. Il fournit une méthode. Plusieurs voix peuvent occuper une même scène sans devenir une seule voix. Preuve scientifique, expérience clinique, architecture technique, pratique institutionnelle et culture peuvent rester distinctes avant d’être interprétées ensemble.","La philosophie italienne apporte une autre discipline. Vico interroge ce que signifie comprendre ce que nous construisons. Machiavel demande comment l’action demeure possible dans des systèmes instables. Croce rappelle que l’histoire se rend toujours présente. Leopardi explore ce qui se passe dans l’esprit lorsque le monde et le désir le débordent.","VOCE utilise ces contrepoints pour résister à deux simplifications: traiter la technologie comme un destin, ou traiter l’humain comme un slogan moral abstrait."],
["06","Ce que produit VOCE","VOCE Research développe recherche formelle et recherche appliquée. Le VOCE AI Governance Institute étudie le passage du modèle au système, les agents, le RAG, l’orchestration, la souveraineté, la sécurité, l’observabilité, la responsabilité et les capacités institutionnelles. Les COURS VOCE® expliquent des mécanismes difficiles dans un format expert compact. Les séries éditoriales relient science, médecine, technologie, culture, infrastructures et comportement humain.","Les séminaires et travaux institutionnels approfondissent certains sujets avec des organisations, des experts et des partenaires culturels. L’objectif reste éducatif et analytique. VOCE ne délivre pas de soins médicaux et ne remplace pas un avis clinique, juridique ou réglementaire."],
["07","No one left unheard","La formule précède l’élargissement actuel de VOCE, mais elle continue de définir l’institution. “No one left unheard” ne signifie pas que toutes les affirmations se valent. Cela signifie que les systèmes doivent être lus en tenant compte des personnes, disciplines et conséquences qu’il est le plus facile de faire disparaître du cadre.","Le rôle de VOCE est de préserver cette pluralité sans abandonner les standards de preuve. La voix compte précisément parce qu’elle est confrontée aux faits, à la méthode et aux autres voix."]
],
linksTitle:"Poursuivre dans VOCE",
links:[
["Research","Comment VOCE distingue recherche formelle, recherche appliquée et analyse éditoriale.","/research.html"],
["Gouvernance & standards","Comment VOCE travaille, vérifie ses sources, traite les limites, corrections et usages de l’IA.","/standards.html"],
["Gouvernance de l’IA","Le parcours technique VOCE consacré aux systèmes d’IA institutionnels.","/governance.html"],
["Publications","Travaux formels, DOI et corpus éditorial VOCE.","/publications.html"]
]
},
it:{
kicker:"Chi è VOCE",
title:"Una casa di ricerca e cultura per i sistemi che trasformano la vita umana.",
deck:"VOCE è un’associazione francese indipendente senza scopo di lucro. Riunisce ricerca applicata, mediazione scientifica e culturale, educazione pubblica e intelligence editoriale per rendere più intelligibili i sistemi contemporanei senza appiattirne la complessità.",
meta:["Parigi","Londra","Dubai","Hangzhou","Shanghai","Hong Kong"],
sections:[
["01","Che cos’è VOCE","VOCE nasce da una convinzione semplice: le grandi trasformazioni della vita contemporanea non rientrano più in una sola disciplina. L’intelligenza artificiale modifica lavoro e responsabilità. Gli ambienti digitali cambiano attenzione e relazioni. La medicina viene trasformata da dati, biomarcatori e software. Cultura e design conservano forme di intelligenza che l’analisi tecnica, da sola, non riesce a spiegare.","VOCE funziona quindi come una casa di indagine più che come un media convenzionale. Studia meccanismi, architetture e conseguenze umane, poi trasforma questo lavoro in ricerca, corsi, briefing, seminari e formati editoriali aperti al pubblico.","L’ambizione non è commentare tutto. È rendere eccezionalmente chiari un numero più limitato di temi difficili."],
["02","L’architettura intellettuale","VOCE collega campi normalmente separati: intelligenza artificiale e governance, neuroscienze e psicologia, salute e medicina, ambienti digitali e comportamento umano, educazione e società, cultura e patrimonio, tecnologia, infrastrutture e lavoro.","Il filo comune è il rapporto tra sistemi e capacità d’azione umana. Che cosa consente una tecnologia? Che cosa delega un’istituzione? Che cosa accade ad attenzione, giudizio, competenza, memoria, linguaggio, fiducia o responsabilità quando cambia un sistema operativo?","Per questo un’analisi VOCE può iniziare da un protocollo tecnico e terminare con una questione di apprendistato, infanzia, cura, trasmissione culturale o legittimità istituzionale."],
["03","La ricerca prima della postura","VOCE non parte da una posizione politica, commerciale o tecnologica per cercare poi le prove che la confermano. Il metodo parte dall’oggetto: studio, architettura, regolazione, infrastruttura, meccanismo clinico, comportamento di piattaforma, oggetto storico o decisione istituzionale.","Il lavoro separa ciò che è documentato da ciò che viene inferito, distingue correlazione e causalità e rende visibili i limiti metodologici. La scrittura deve restare comprensibile a un non specialista senza ridurre la sostanza tecnica.","I risultati di ricerca formali vengono distinti dall’analisi editoriale. VOCE Research pubblica, quando appropriato, con identificatori persistenti; il corpus editoriale VOCE interpreta evidenze e sistemi recenti per un pubblico più ampio."],
["04","Un comitato scientifico dentro gli ecosistemi","VOCE si appoggia a un comitato scientifico e a una rete di esperti i cui membri e contributori lavorano negli ambienti studiati. La rete riunisce professionisti della tecnologia, psichiatri, attori culturali, artisti, persone attive con fondazioni e istituzioni ed esperti esposti a differenti sistemi regionali.","Parigi e Londra portano profondità istituzionale, finanziaria, culturale e scientifica. Dubai offre un punto di osservazione del Golfo in cui infrastrutture, capitale e adozione tecnologica avanzano rapidamente. Hangzhou, Shanghai e Hong Kong offrono prospettive cinesi differenti su piattaforme, commercio, industria, finanza, lusso, tecnologia e sistemi transfrontalieri.","Questa geografia serve un’intelligenza comparativa. VOCE non assume un solo mercato come modello predefinito del mondo."],
["05","Opera, filosofia e metodo VOCE","L’opera non è uno strato decorativo del marchio. Offre un metodo. Più voci possono occupare la stessa scena senza diventare la stessa voce. Evidenza scientifica, esperienza clinica, architettura tecnica, pratica istituzionale e cultura possono restare distinte prima di essere interpretate insieme.","La filosofia italiana aggiunge un’altra disciplina. Vico interroga cosa significhi comprendere ciò che costruiamo. Machiavelli chiede come l’azione resti possibile dentro sistemi instabili. Croce ricorda come la storia si renda presente. Leopardi esplora ciò che accade nella mente quando mondo e desiderio la oltrepassano.","VOCE usa questi contrappunti per resistere a due semplificazioni: trattare la tecnologia come destino, o l’umano come slogan morale astratto."],
["06","Che cosa produce VOCE","VOCE Research sviluppa ricerca formale e applicata. Il VOCE AI Governance Institute studia il passaggio dal modello al sistema, agenti, RAG, orchestrazione, sovranità, sicurezza, osservabilità, responsabilità e capacità istituzionale. I CORSI VOCE® spiegano meccanismi difficili in un formato esperto compatto. Le serie editoriali collegano scienza, medicina, tecnologia, cultura, infrastrutture e comportamento umano.","Seminari e lavori istituzionali approfondiscono temi selezionati con organizzazioni, esperti e partner culturali. L’obiettivo resta educativo e analitico. VOCE non fornisce cure mediche e non sostituisce consulenza clinica, legale o regolamentare."],
["07","No one left unheard","La formula precede l’attuale ampliamento di VOCE, ma continua a definire l’istituzione. “No one left unheard” non significa che tutte le affermazioni siano equivalenti. Significa che i sistemi devono essere letti prestando attenzione a persone, discipline e conseguenze che è più facile rimuovere dal quadro.","Il ruolo di VOCE è preservare questa pluralità senza abbandonare gli standard di evidenza. La voce conta proprio perché viene confrontata con fatti, metodo e altre voci."]
],
linksTitle:"Continuare dentro VOCE",
links:[
["Research","Come VOCE distingue ricerca formale, ricerca applicata e analisi editoriale.","/research.html"],
["Governance & standard","Come VOCE lavora, verifica le fonti, tratta limiti, correzioni e uso dell’IA.","/standards.html"],
["Governance dell’IA","Il percorso tecnico VOCE sui sistemi di IA istituzionali.","/governance.html"],
["Pubblicazioni","Ricerca formale, DOI e corpus editoriale VOCE.","/publications.html"]
]
}
},
standards:{
en:{kicker:"Governance & Standards",title:"How VOCE works: evidence, independence and institutional discipline.",deck:"VOCE’s credibility depends less on the breadth of its subjects than on the consistency of the method applied to them.",meta:["Sources","Method","Corrections","AI use","Independence"],sections:[
["01","Source hierarchy","VOCE gives priority to primary or near-primary sources: peer-reviewed research, official datasets, technical documentation, regulations, institutional reports, trial registries, infrastructure specifications and first-party disclosures. Secondary reporting is useful for discovery and context, but it should not silently replace the underlying source.","For contemporary subjects, recency matters. A historical study can remain important, but VOCE avoids presenting older evidence as if it described the current technological, clinical or institutional environment."],
["02","Evidence and interpretation","Every VOCE text should make it possible to distinguish documented facts, methodological interpretation and editorial analysis. Correlation is not presented as causality. Small samples, proxy measures, laboratory settings, geographic limits and conflicts of interest matter.","The purpose is not to make every article timid. It is to make strong claims only where the evidentiary structure can support them."],
["03","Scientific committee and expert review","The scientific committee and expert network provide disciplinary challenge rather than decorative prestige. Their role is to test mechanisms, expose blind spots, question terminology and help VOCE avoid ideological, emotional or commercial drift.","VOCE’s international vantage points also act as a methodological check: an assumption that appears universal in Paris may look different in Dubai, Hangzhou, Shanghai or Hong Kong."],
["04","Corrections, versions and traceability","Research outputs should preserve versions, citations and persistent identifiers where appropriate. Editorial work should be corrected when material errors are identified. A correction is not treated as reputational failure; it is part of research discipline.","For technical and regulatory material, the date of the claim matters because systems, models and rules change quickly."],
["05","Use of artificial intelligence","VOCE can use AI as a research and production instrument for retrieval, comparison, drafting, translation, coding or workflow support. AI output is not treated as a source. Claims that matter must be grounded in identifiable evidence, and human responsibility remains with the person or institution publishing the work.","For AI-governance research in particular, VOCE applies to itself the distinction it makes elsewhere: a model can assist cognition, but authority and accountability must remain explicit."],
["06","Independence, conflicts and funding","VOCE’s editorial and research independence should remain distinguishable from commercial, institutional or philanthropic relationships. Where a relationship materially affects a publication or project, it should be disclosed.","The standard is not the absence of partners. It is the ability to preserve method, attribution and the right to publish conclusions that are not dictated by a partner’s interests."],
["07","Scope and limits","VOCE is an educational, research and cultural institution. It does not provide medical diagnosis or treatment, and its publications do not replace professional clinical, legal, financial or regulatory advice.","This boundary allows VOCE to work seriously on health, psychiatry, governance and institutions without confusing public knowledge with professional care."]
],linksTitle:"Related VOCE pathways",links:[["About VOCE","Mission, intellectual architecture and expert network.","/about.html"],["AI Governance","Technical governance from models to operating systems.","/governance.html"],["Research","Formal research, applied research and editorial intelligence.","/research.html"],["Publications","DOI outputs and VOCE’s wider corpus.","/publications.html"]]},
fr:{kicker:"Gouvernance & standards",title:"Comment travaille VOCE: preuve, indépendance et discipline institutionnelle.",deck:"La crédibilité de VOCE dépend moins de l’étendue de ses sujets que de la constance de la méthode appliquée à chacun d’eux.",meta:["Sources","Méthode","Corrections","Usage de l’IA","Indépendance"],sections:[
["01","Hiérarchie des sources","VOCE donne la priorité aux sources primaires ou proches des sources primaires: recherche évaluée par les pairs, jeux de données officiels, documentation technique, réglementations, rapports institutionnels, registres d’essais, spécifications d’infrastructure et publications de première partie. La presse secondaire sert à découvrir et contextualiser, mais ne doit pas remplacer silencieusement la source sous-jacente.","Pour les sujets contemporains, la fraîcheur compte. Une étude ancienne peut rester historiquement importante, mais VOCE évite de la présenter comme description directe d’un environnement technologique, clinique ou institutionnel actuel."],
["02","Preuve et interprétation","Chaque texte VOCE doit permettre de distinguer les faits documentés, l’interprétation méthodologique et l’analyse éditoriale. Une corrélation n’est pas présentée comme causalité. Taille d’échantillon, mesures indirectes, conditions de laboratoire, limites géographiques et conflits d’intérêts comptent.","L’objectif n’est pas de rendre chaque article timide. Il est de ne formuler des affirmations fortes que lorsque la structure des preuves peut les soutenir."],
["03","Comité scientifique et regard expert","Le comité scientifique et le réseau d’experts apportent une contradiction disciplinaire, pas un prestige décoratif. Leur rôle est de tester les mécanismes, révéler les angles morts, questionner les termes et aider VOCE à éviter les dérives idéologiques, émotionnelles ou commerciales.","Les différents points d’observation internationaux jouent aussi comme contrôle méthodologique: une hypothèse qui semble universelle à Paris peut apparaître autrement à Dubaï, Hangzhou, Shanghai ou Hong Kong."],
["04","Corrections, versions et traçabilité","Les travaux de recherche doivent conserver versions, citations et identifiants persistants lorsque cela est pertinent. Les textes éditoriaux doivent être corrigés lorsqu’une erreur matérielle est identifiée. Une correction n’est pas considérée comme un échec réputationnel; elle fait partie de la discipline de recherche.","Pour les sujets techniques et réglementaires, la date de l’affirmation compte car systèmes, modèles et règles évoluent rapidement."],
["05","Usage de l’intelligence artificielle","VOCE peut utiliser l’IA comme instrument de recherche et de production pour la recherche documentaire, la comparaison, la rédaction, la traduction, le code ou l’organisation des flux de travail. Une sortie d’IA n’est pas traitée comme une source. Les affirmations importantes doivent être ancrées dans des preuves identifiables, et la responsabilité humaine reste attachée à la personne ou à l’institution qui publie.","Pour la gouvernance de l’IA en particulier, VOCE s’applique la distinction qu’elle formule ailleurs: un modèle peut assister la cognition, mais l’autorité et la responsabilité doivent rester explicites."],
["06","Indépendance, conflits et financement","L’indépendance éditoriale et scientifique de VOCE doit rester distinguable de ses relations commerciales, institutionnelles ou philanthropiques. Lorsqu’une relation affecte matériellement une publication ou un projet, elle doit être signalée.","Le standard n’est pas l’absence de partenaires. C’est la capacité à préserver méthode, attribution et droit de publier des conclusions non dictées par les intérêts d’un partenaire."],
["07","Périmètre et limites","VOCE est une institution éducative, scientifique et culturelle. Elle ne délivre ni diagnostic ni traitement médical, et ses publications ne remplacent pas un avis clinique, juridique, financier ou réglementaire professionnel.","Cette frontière permet à VOCE de travailler sérieusement sur santé, psychiatrie, gouvernance et institutions sans confondre connaissance publique et prise en charge professionnelle."]
],linksTitle:"Parcours VOCE associés",links:[["À propos de VOCE","Mission, architecture intellectuelle et réseau d’experts.","/about.html"],["Gouvernance de l’IA","Gouvernance technique du modèle au système opérationnel.","/governance.html"],["Research","Recherche formelle, recherche appliquée et intelligence éditoriale.","/research.html"],["Publications","DOI et corpus VOCE.","/publications.html"]]},
it:{kicker:"Governance & standard",title:"Come lavora VOCE: evidenza, indipendenza e disciplina istituzionale.",deck:"La credibilità di VOCE dipende meno dall’ampiezza dei temi che dalla coerenza del metodo applicato a ciascuno di essi.",meta:["Fonti","Metodo","Correzioni","Uso dell’IA","Indipendenza"],sections:[
["01","Gerarchia delle fonti","VOCE privilegia fonti primarie o prossime alle primarie: ricerca peer-reviewed, dati ufficiali, documentazione tecnica, regolamentazioni, rapporti istituzionali, registri di trial, specifiche infrastrutturali e comunicazioni di prima parte. Il reporting secondario è utile per scoperta e contesto, ma non deve sostituire silenziosamente la fonte sottostante.","Per i temi contemporanei la recenza conta. Uno studio storico può restare importante, ma VOCE evita di presentare evidenze datate come descrizione diretta dell’ambiente tecnologico, clinico o istituzionale attuale."],
["02","Evidenza e interpretazione","Ogni testo VOCE dovrebbe permettere di distinguere fatti documentati, interpretazione metodologica e analisi editoriale. La correlazione non viene presentata come causalità. Dimensione del campione, proxy, contesto di laboratorio, limiti geografici e conflitti d’interesse contano.","Lo scopo non è rendere ogni articolo prudente fino all’irrilevanza. È formulare affermazioni forti soltanto quando la struttura delle evidenze le sostiene."],
["03","Comitato scientifico e revisione esperta","Il comitato scientifico e la rete di esperti offrono confronto disciplinare, non prestigio decorativo. Il loro ruolo è testare i meccanismi, far emergere punti ciechi, interrogare la terminologia e aiutare VOCE a evitare derive ideologiche, emotive o commerciali.","I diversi punti di osservazione internazionali funzionano anche come controllo metodologico: un’ipotesi che sembra universale a Parigi può apparire diversa a Dubai, Hangzhou, Shanghai o Hong Kong."],
["04","Correzioni, versioni e tracciabilità","I risultati di ricerca dovrebbero conservare versioni, citazioni e identificatori persistenti quando appropriato. Il lavoro editoriale viene corretto quando emergono errori materiali. Una correzione non è trattata come fallimento reputazionale; è parte della disciplina della ricerca.","Per materiali tecnici e regolamentari, la data dell’affermazione conta perché sistemi, modelli e regole cambiano rapidamente."],
["05","Uso dell’intelligenza artificiale","VOCE può usare l’IA come strumento di ricerca e produzione per retrieval, confronto, redazione, traduzione, coding o supporto ai workflow. L’output di un modello non viene trattato come una fonte. Le affermazioni rilevanti devono essere ancorate a evidenze identificabili e la responsabilità umana resta in capo alla persona o istituzione che pubblica.","Nella ricerca sulla governance dell’IA, VOCE applica a se stessa la distinzione formulata altrove: un modello può assistere la cognizione, ma autorità e responsabilità devono restare esplicite."],
["06","Indipendenza, conflitti e finanziamento","L’indipendenza editoriale e scientifica di VOCE deve restare distinguibile dalle relazioni commerciali, istituzionali o filantropiche. Quando una relazione influisce materialmente su una pubblicazione o un progetto, dovrebbe essere dichiarata.","Lo standard non è l’assenza di partner. È la capacità di preservare metodo, attribuzione e diritto di pubblicare conclusioni non dettate dagli interessi di un partner."],
["07","Ambito e limiti","VOCE è un’istituzione educativa, di ricerca e culturale. Non fornisce diagnosi o trattamenti medici e le sue pubblicazioni non sostituiscono consulenza clinica, legale, finanziaria o regolamentare professionale.","Questo confine permette a VOCE di lavorare seriamente su salute, psichiatria, governance e istituzioni senza confondere conoscenza pubblica e cura professionale."]
],linksTitle:"Percorsi VOCE collegati",links:[["Chi è VOCE","Missione, architettura intellettuale e rete di esperti.","/about.html"],["Governance dell’IA","Governance tecnica dal modello al sistema operativo.","/governance.html"],["Research","Ricerca formale, ricerca applicata e intelligence editoriale.","/research.html"],["Pubblicazioni","DOI e corpus VOCE.","/publications.html"]]}
},
research:{
en:{kicker:"VOCE Research",title:"Research that moves from mechanism to human consequence.",deck:"VOCE distinguishes formal research, applied research and editorial intelligence while allowing them to inform one another.",meta:["Digital environments","AI & work","Health","Culture","Human behaviour"],sections:[
["01","Formal research","Formal research outputs use stable authorship, references, versioning and persistent identifiers where appropriate. Current work includes parental technoference and early language development, and the relationship between continuous digital stimulation and inner thinking.","The purpose is not volume. It is to create a small body of work whose method and claims can be inspected."],
["02","Applied research","Applied research follows mechanisms into operating environments. In AI governance, that means moving beyond model benchmarks to permissions, agents, RAG, tools, security, observability, FinOps and human accountability. In work, it means examining how agents change task architecture, productivity, apprenticeship and expertise.","In health and human behaviour, it means connecting biomarkers, diagnostics, attention, memory, relationships, platform design and lived experience without confusing public analysis with clinical care."],
["03","Editorial intelligence","VOCE’s editorial work is a research interface. It translates recent studies, technical systems, infrastructures and institutional changes into compact analysis without turning them into simplified news.","The recurring editorial test is: “I knew the subject, but not this.” The value lies in exposing a mechanism or detail that changes the reader’s mental model."],
["04","COURS VOCE®","COURS VOCE® is the explanatory layer. A course isolates one mechanism, defines the architecture, names the relevant metrics or controls, and shows how the subject connects to a wider system.","The format is deliberately compact. It is designed to be useful to readers who need more than a headline but less than a full academic paper."],
["05","Research geography","VOCE’s research is informed by different operating ecosystems. Europe provides dense regulatory and institutional contexts. Dubai provides a Gulf perspective shaped by infrastructure and rapid adoption. Hangzhou, Shanghai and Hong Kong expose different Chinese technology, commercial, industrial and financial systems.","Comparison is used to test assumptions, not to manufacture superficial internationalism."],
["06","Research agenda","The current agenda spans AI governance, sovereignty and orchestration, light workforce, technoference, cognition, attention, memory, health and medicine, education, culture, heritage, infrastructure and the changing relationship between people and machines.","These are not independent verticals. VOCE treats them as interacting layers of one contemporary system."]
],linksTitle:"Explore the research",links:[["AI Governance","Agents, RAG, permissions, orchestration, security and accountability.","/governance.html"],["Sovereignty","Open models, cognitive supply chains and strategic switching capacity.","/sovereignty.html"],["Light workforce","Automation, productivity, apprenticeship and expertise.","/light-workforce.html"],["Technoference","Attention, language, memory, relationships and digital interruption.","/technoference.html"]]},
fr:{kicker:"VOCE Research",title:"Une recherche qui va du mécanisme jusqu’à la conséquence humaine.",deck:"VOCE distingue recherche formelle, recherche appliquée et intelligence éditoriale tout en les laissant s’informer mutuellement.",meta:["Environnements numériques","IA & travail","Santé","Culture","Comportement humain"],sections:[
["01","Recherche formelle","Les travaux formels reposent sur une attribution stable, des références, un suivi des versions et des identifiants persistants lorsque cela est pertinent. Les travaux actuels incluent la technoference parentale et le développement précoce du langage, ainsi que la relation entre stimulation numérique continue et pensée intérieure.","L’objectif n’est pas le volume. Il s’agit de constituer un corpus limité dont la méthode et les affirmations peuvent être examinées."],
["02","Recherche appliquée","La recherche appliquée suit les mécanismes jusque dans les environnements opérationnels. En gouvernance de l’IA, cela signifie dépasser les benchmarks de modèles pour étudier permissions, agents, RAG, outils, sécurité, observabilité, FinOps et responsabilité humaine. Dans le travail, cela signifie analyser comment les agents transforment architecture des tâches, productivité, apprentissage et expertise.","En santé et comportement humain, cela signifie relier biomarqueurs, diagnostic, attention, mémoire, relations, design des plateformes et expérience vécue sans confondre analyse publique et prise en charge clinique."],
["03","Intelligence éditoriale","Le travail éditorial VOCE est une interface de recherche. Il traduit études récentes, systèmes techniques, infrastructures et changements institutionnels en analyses compactes sans les réduire à de l’actualité simplifiée.","Le test éditorial récurrent est: “je connaissais le sujet, mais pas ça”. La valeur vient du mécanisme ou du détail qui modifie le modèle mental du lecteur."],
["04","COURS VOCE®","COURS VOCE® constitue la couche explicative. Un cours isole un mécanisme, définit l’architecture, nomme les métriques ou contrôles pertinents et montre comment le sujet s’insère dans un système plus large.","Le format est volontairement compact. Il est pensé pour des lecteurs qui ont besoin de davantage qu’un titre, mais de moins qu’un article académique complet."],
["05","Géographie de recherche","La recherche VOCE est nourrie par plusieurs écosystèmes opérationnels. L’Europe apporte des contextes réglementaires et institutionnels denses. Dubaï apporte une perspective du Golfe façonnée par l’infrastructure et l’adoption rapide. Hangzhou, Shanghai et Hong Kong exposent des systèmes chinois technologiques, commerciaux, industriels et financiers différents.","La comparaison sert à tester des hypothèses, pas à fabriquer un internationalisme superficiel."],
["06","Agenda de recherche","L’agenda actuel couvre gouvernance de l’IA, souveraineté et orchestration, light workforce, technoference, cognition, attention, mémoire, santé et médecine, éducation, culture, patrimoine, infrastructures et évolution de la relation entre personnes et machines.","Ces sujets ne sont pas des verticales indépendantes. VOCE les traite comme les couches interactives d’un même système contemporain."]
],linksTitle:"Explorer la recherche",links:[["Gouvernance de l’IA","Agents, RAG, permissions, orchestration, sécurité et responsabilité.","/governance.html"],["Souveraineté","Modèles ouverts, chaîne cognitive et capacité stratégique de changement.","/sovereignty.html"],["Light workforce","Automatisation, productivité, apprentissage et expertise.","/light-workforce.html"],["Technoference","Attention, langage, mémoire, relations et interruption numérique.","/technoference.html"]]},
it:{kicker:"VOCE Research",title:"Una ricerca che va dal meccanismo alla conseguenza umana.",deck:"VOCE distingue ricerca formale, ricerca applicata e intelligence editoriale lasciando che si informino reciprocamente.",meta:["Ambienti digitali","IA & lavoro","Salute","Cultura","Comportamento umano"],sections:[
["01","Ricerca formale","I risultati formali utilizzano attribuzione stabile, riferimenti, versioning e identificatori persistenti quando appropriato. I lavori attuali includono technoference parentale e sviluppo precoce del linguaggio, e la relazione tra stimolazione digitale continua e pensiero interiore.","L’obiettivo non è il volume. È creare un corpus limitato in cui metodo e affermazioni possano essere esaminati."],
["02","Ricerca applicata","La ricerca applicata segue i meccanismi dentro gli ambienti operativi. Nella governance dell’IA significa andare oltre i benchmark dei modelli per studiare permessi, agenti, RAG, strumenti, sicurezza, osservabilità, FinOps e responsabilità umana. Nel lavoro significa osservare come gli agenti cambiano architettura dei compiti, produttività, apprendistato e competenza.","In salute e comportamento umano significa collegare biomarcatori, diagnosi, attenzione, memoria, relazioni, design delle piattaforme ed esperienza vissuta senza confondere analisi pubblica e cura clinica."],
["03","Intelligence editoriale","Il lavoro editoriale VOCE è un’interfaccia di ricerca. Traduce studi recenti, sistemi tecnici, infrastrutture e cambiamenti istituzionali in analisi compatte senza ridurli a notizie semplificate.","Il test editoriale ricorrente è: “conoscevo l’argomento, ma non questo”. Il valore sta nel meccanismo o dettaglio che cambia il modello mentale del lettore."],
["04","CORSI VOCE®","CORSI VOCE® è il livello esplicativo. Un corso isola un meccanismo, definisce l’architettura, nomina metriche o controlli rilevanti e mostra come il tema si collega a un sistema più ampio.","Il formato è volutamente compatto. È pensato per lettori che hanno bisogno di più di un titolo ma meno di un paper accademico completo."],
["05","Geografia della ricerca","La ricerca VOCE è informata da diversi ecosistemi operativi. L’Europa offre contesti regolamentari e istituzionali densi. Dubai offre una prospettiva del Golfo plasmata da infrastrutture e adozione rapida. Hangzhou, Shanghai e Hong Kong espongono sistemi cinesi tecnologici, commerciali, industriali e finanziari differenti.","Il confronto serve a testare ipotesi, non a produrre un internazionalismo superficiale."],
["06","Agenda di ricerca","L’agenda attuale comprende governance dell’IA, sovranità e orchestrazione, light workforce, technoference, cognizione, attenzione, memoria, salute e medicina, educazione, cultura, patrimonio, infrastrutture e cambiamento del rapporto tra persone e macchine.","Non sono verticali indipendenti. VOCE li tratta come livelli interagenti di un unico sistema contemporaneo."]
],linksTitle:"Esplora la ricerca",links:[["Governance dell’IA","Agenti, RAG, permessi, orchestrazione, sicurezza e responsabilità.","/governance.html"],["Sovranità","Modelli aperti, catena cognitiva e capacità strategica di cambiamento.","/sovereignty.html"],["Light workforce","Automazione, produttività, apprendistato e competenza.","/light-workforce.html"],["Technoference","Attenzione, linguaggio, memoria, relazioni e interruzione digitale.","/technoference.html"]]}
},
publications:{
en:{kicker:"Publications",title:"A corpus designed to remain inspectable.",deck:"VOCE separates formal research outputs from editorial analysis while giving both a clear place in the institution.",meta:["DOI","Research","Courses","Editorial series"],sections:[
["01","Formal research outputs","VOCE Research publishes work with stable references and persistent identifiers where appropriate. Two current outputs are listed below.","When digital stimulation disrupts inner thinking · DOI 10.5281/zenodo.19189281","How parental technoference affects early language development · DOI 10.5281/zenodo.19114381"],
["02","Editorial corpus","VOCE’s editorial corpus spans artificial intelligence, health, neuroscience, psychology, technology, infrastructure, culture, logistics, medicine, education and human behaviour. These texts are not presented as peer-reviewed papers unless they are formal research outputs.","Their function is interpretive: identify an overlooked mechanism, explain why it matters and preserve the chain back to the source."],
["03","COURS VOCE®","The course format converts a difficult subject into an expert explanatory unit: mechanism, architecture, vocabulary, controls, metrics and implications.","Topics increasingly include AI systems, governance, agents, RAG, model routing, sovereignty, infrastructure, workforce transformation and the cognitive effects of digital environments."],
["04","Versions and archive","VOCE is building a canonical institutional archive so that research outputs, courses and major editorial texts can be located by subject, date, source and version.","The website is intended to become that source of record rather than leaving the institution dependent on social platforms."]
],linksTitle:"Direct access",links:[["Digital stimulation & inner thinking","Open DOI record.","https://doi.org/10.5281/zenodo.19189281"],["Parental technoference & language","Open DOI record.","https://doi.org/10.5281/zenodo.19114381"],["VOCE Research","Research architecture and current agenda.","/research.html"],["LinkedIn","Current public editorial stream.","https://fr.linkedin.com/in/voce-association-0030763b6"]]},
fr:{kicker:"Publications",title:"Un corpus conçu pour rester vérifiable.",deck:"VOCE sépare les travaux de recherche formels de l’analyse éditoriale tout en donnant à chacun une place claire dans l’institution.",meta:["DOI","Recherche","Cours","Séries éditoriales"],sections:[
["01","Travaux de recherche formels","VOCE Research publie des travaux avec références stables et identifiants persistants lorsque cela est pertinent. Deux travaux actuels sont présentés ci-dessous.","Quand la stimulation numérique perturbe la pensée intérieure · DOI 10.5281/zenodo.19189281","Comment la technoference parentale affecte le développement précoce du langage · DOI 10.5281/zenodo.19114381"],
["02","Corpus éditorial","Le corpus éditorial VOCE traverse intelligence artificielle, santé, neurosciences, psychologie, technologie, infrastructures, culture, logistique, médecine, éducation et comportement humain. Ces textes ne sont pas présentés comme des publications évaluées par les pairs lorsqu’ils ne relèvent pas de la recherche formelle.","Leur fonction est interprétative: identifier un mécanisme négligé, expliquer pourquoi il compte et préserver la chaîne qui ramène à la source."],
["03","COURS VOCE®","Le format COURS VOCE® transforme un sujet difficile en unité explicative experte: mécanisme, architecture, vocabulaire, contrôles, métriques et implications.","Les thèmes couvrent de plus en plus les systèmes d’IA, la gouvernance, les agents, le RAG, le routage des modèles, la souveraineté, les infrastructures, la transformation du travail et les effets cognitifs des environnements numériques."],
["04","Versions et archive","VOCE construit une archive institutionnelle canonique afin que recherches, cours et textes éditoriaux majeurs puissent être retrouvés par sujet, date, source et version.","Le site a vocation à devenir cette source de référence plutôt que de laisser l’institution dépendre des plateformes sociales."]
],linksTitle:"Accès direct",links:[["Stimulation numérique & pensée intérieure","Ouvrir le DOI.","https://doi.org/10.5281/zenodo.19189281"],["Technoference parentale & langage","Ouvrir le DOI.","https://doi.org/10.5281/zenodo.19114381"],["VOCE Research","Architecture de recherche et agenda actuel.","/research.html"],["LinkedIn","Flux éditorial public actuel.","https://fr.linkedin.com/in/voce-association-0030763b6"]]},
it:{kicker:"Pubblicazioni",title:"Un corpus progettato per restare verificabile.",deck:"VOCE separa i risultati formali di ricerca dall’analisi editoriale dando a entrambi un posto chiaro nell’istituzione.",meta:["DOI","Ricerca","Corsi","Serie editoriali"],sections:[
["01","Risultati formali di ricerca","VOCE Research pubblica lavori con riferimenti stabili e identificatori persistenti quando appropriato. Due risultati attuali sono indicati qui sotto.","Quando la stimolazione digitale interrompe il pensiero interiore · DOI 10.5281/zenodo.19189281","Come la technoference parentale influenza lo sviluppo precoce del linguaggio · DOI 10.5281/zenodo.19114381"],
["02","Corpus editoriale","Il corpus editoriale VOCE attraversa intelligenza artificiale, salute, neuroscienze, psicologia, tecnologia, infrastrutture, cultura, logistica, medicina, educazione e comportamento umano. Questi testi non vengono presentati come paper peer-reviewed quando non sono risultati formali di ricerca.","La loro funzione è interpretativa: identificare un meccanismo trascurato, spiegare perché conta e preservare la catena che ritorna alla fonte."],
["03","CORSI VOCE®","Il formato CORSI VOCE® trasforma un tema difficile in un’unità esplicativa esperta: meccanismo, architettura, vocabolario, controlli, metriche e implicazioni.","I temi includono sempre più sistemi IA, governance, agenti, RAG, routing dei modelli, sovranità, infrastrutture, trasformazione del lavoro ed effetti cognitivi degli ambienti digitali."],
["04","Versioni e archivio","VOCE sta costruendo un archivio istituzionale canonico affinché ricerca, corsi e principali testi editoriali possano essere ritrovati per tema, data, fonte e versione.","Il sito è destinato a diventare questa fonte di riferimento invece di lasciare l’istituzione dipendente dalle piattaforme sociali."]
],linksTitle:"Accesso diretto",links:[["Stimolazione digitale & pensiero interiore","Apri il DOI.","https://doi.org/10.5281/zenodo.19189281"],["Technoference parentale & linguaggio","Apri il DOI.","https://doi.org/10.5281/zenodo.19114381"],["VOCE Research","Architettura di ricerca e agenda attuale.","/research.html"],["LinkedIn","Flusso editoriale pubblico attuale.","https://fr.linkedin.com/in/voce-association-0030763b6"]]}
},
contact:{
en:{kicker:"Contact",title:"Research, institutions, culture.",deck:"VOCE welcomes serious exchanges with researchers, institutions, foundations, cultural organisations and practitioners working on the systems it studies.",meta:["Paris","London","Dubai","China"],sections:[
["01","VOCE Association","Registered office: 94 rue Montmartre, 75002 Paris, France.","Email: contact@voce.life","LinkedIn: VOCE Association"],
["02","Research & expertise","For research dialogue, scientific committee exchanges, source corrections or expert contribution, contact VOCE with the subject area and the nature of the contribution.","VOCE prioritises exchanges that add evidence, challenge a mechanism or provide direct knowledge of an ecosystem."],
["03","Institutional & cultural work","VOCE can engage with institutions, foundations and cultural organisations around research, seminars, scientific and cultural mediation, AI governance, digital environments and the human consequences of technological change.","The approach remains research-led rather than promotional."]
],linksTitle:"Start from a VOCE pathway",links:[["About VOCE","Understand the institution first.","/about.html"],["Research","Current agenda and methods.","/research.html"],["Governance & Standards","Method, evidence and independence.","/standards.html"],["LinkedIn","Follow current editorial work.","https://fr.linkedin.com/in/voce-association-0030763b6"]]},
fr:{kicker:"Contact",title:"Recherche, institutions, culture.",deck:"VOCE accueille les échanges sérieux avec chercheurs, institutions, fondations, organisations culturelles et praticiens travaillant sur les systèmes qu’elle étudie.",meta:["Paris","Londres","Dubaï","Chine"],sections:[
["01","VOCE Association","Siège social: 94 rue Montmartre, 75002 Paris, France.","Email: contact@voce.life","LinkedIn: VOCE Association"],
["02","Recherche & expertise","Pour un échange de recherche, une contribution au comité scientifique, une correction de source ou un apport expert, contacter VOCE en précisant le domaine et la nature de la contribution.","VOCE privilégie les échanges qui ajoutent une preuve, contestent utilement un mécanisme ou apportent une connaissance directe d’un écosystème."],
["03","Travail institutionnel & culturel","VOCE peut travailler avec institutions, fondations et organisations culturelles autour de la recherche, des séminaires, de la médiation scientifique et culturelle, de la gouvernance de l’IA, des environnements numériques et des conséquences humaines du changement technologique.","L’approche reste guidée par la recherche plutôt que par la promotion."]
],linksTitle:"Entrer dans VOCE",links:[["À propos de VOCE","Comprendre d’abord l’institution.","/about.html"],["Research","Agenda actuel et méthodes.","/research.html"],["Gouvernance & standards","Méthode, preuve et indépendance.","/standards.html"],["LinkedIn","Suivre le travail éditorial actuel.","https://fr.linkedin.com/in/voce-association-0030763b6"]]},
it:{kicker:"Contatti",title:"Ricerca, istituzioni, cultura.",deck:"VOCE accoglie scambi seri con ricercatori, istituzioni, fondazioni, organizzazioni culturali e professionisti che lavorano sui sistemi studiati.",meta:["Parigi","Londra","Dubai","Cina"],sections:[
["01","VOCE Association","Sede legale: 94 rue Montmartre, 75002 Parigi, Francia.","Email: contact@voce.life","LinkedIn: VOCE Association"],
["02","Ricerca & competenza","Per dialogo di ricerca, scambi con il comitato scientifico, correzioni di fonti o contributi esperti, contattare VOCE indicando l’area e la natura del contributo.","VOCE privilegia scambi che aggiungono evidenza, mettono utilmente alla prova un meccanismo o portano conoscenza diretta di un ecosistema."],
["03","Lavoro istituzionale & culturale","VOCE può lavorare con istituzioni, fondazioni e organizzazioni culturali su ricerca, seminari, mediazione scientifica e culturale, governance dell’IA, ambienti digitali e conseguenze umane del cambiamento tecnologico.","L’approccio resta guidato dalla ricerca e non dalla promozione."]
],linksTitle:"Entrare in VOCE",links:[["Chi è VOCE","Comprendere prima l’istituzione.","/about.html"],["Research","Agenda attuale e metodi.","/research.html"],["Governance & standard","Metodo, evidenza e indipendenza.","/standards.html"],["LinkedIn","Segui il lavoro editoriale attuale.","https://fr.linkedin.com/in/voce-association-0030763b6"]]}
}
};
const COMMON={
en:{navThemes:"Themes",navResearch:"Research",navStandards:"Standards",navPublications:"Publications",navAbout:"About",links:"Continue",institution:"Institution",work:"Work",contact:"Contact",home:"Home",linkedin:"LinkedIn"},
fr:{navThemes:"Thèmes",navResearch:"Research",navStandards:"Standards",navPublications:"Publications",navAbout:"À propos",links:"Poursuivre",institution:"Institution",work:"Travail",contact:"Contact",home:"Accueil",linkedin:"LinkedIn"},
it:{navThemes:"Temi",navResearch:"Research",navStandards:"Standard",navPublications:"Pubblicazioni",navAbout:"Chi siamo",links:"Continua",institution:"Istituzione",work:"Lavoro",contact:"Contatti",home:"Home",linkedin:"LinkedIn"}
};
function currentLang(){return localStorage.getItem("voce-lang")||"en"}
function renderInstitution(l){
 const p=PAGES[window.VOCE_PAGE][l]||PAGES[window.VOCE_PAGE].en;
 const c=COMMON[l]||COMMON.en;
 document.documentElement.lang=l;
 document.title=p.title+" — VOCE";
 document.querySelectorAll("[data-lang]").forEach(b=>b.classList.toggle("active",b.dataset.lang===l));
 document.querySelector("[data-nav-research]").textContent=c.navResearch;
 document.querySelector("[data-nav-standards]").textContent=c.navStandards;
 document.querySelector("[data-nav-publications]").textContent=c.navPublications;
 document.querySelector("[data-nav-about]").textContent=c.navAbout;
 document.querySelector("#page-kicker").textContent=p.kicker;
 document.querySelector("#page-title").textContent=p.title;
 document.querySelector("#page-deck").textContent=p.deck;
 document.querySelector("#page-meta").innerHTML=p.meta.map(x=>'<span>'+x+'</span>').join("");
 const sections=document.querySelector("#sections");
 sections.innerHTML=p.sections.map(s=>'<section class="chapter"><div class="chapter-no">'+s[0]+'</div><h2>'+s[1]+'</h2>'+s.slice(2).map((x,i)=>'<p'+(i===0&&s.length>4?' class="signal"':'')+'>'+x+'</p>').join("")+'</section>').join("");
 document.querySelector("#links-title").textContent=p.linksTitle;
 document.querySelector("#links").innerHTML=p.links.map(x=>'<a class="link-row" href="'+x[2]+'"'+(x[2].startsWith("http")?' target="_blank" rel="noopener"':'')+'><div class="label">'+c.links+'</div><div><h3>'+x[0]+'</h3><p>'+x[1]+'</p></div><div class="go">'+(l==="fr"?"Ouvrir":l==="it"?"Apri":"Open")+'</div></a>').join("");
 document.querySelector("#f-inst").textContent=c.institution;
 document.querySelector("#f-work").textContent=c.work;
 document.querySelector("#f-about").textContent=c.navAbout;
 document.querySelector("#f-standards").textContent=c.navStandards;
 document.querySelector("#f-contact").textContent=c.contact;
 document.querySelector("#f-research").textContent=c.navResearch;
 document.querySelector("#f-ai").textContent=l==="fr"?"Gouvernance de l’IA":l==="it"?"Governance dell’IA":"AI Governance";
 document.querySelector("#f-pubs").textContent=c.navPublications;
}
function setLang(l){localStorage.setItem("voce-lang",l);renderInstitution(l)}
document.addEventListener("DOMContentLoaded",()=>{
 document.querySelectorAll("[data-lang]").forEach(b=>b.addEventListener("click",()=>setLang(b.dataset.lang)));
 renderInstitution(currentLang());
});