const PAGES={
about:{
en:{
kicker:"About VOCE",
title:"A research, cultural and orchestration institution for complex systems.",
deck:"VOCE brings specialists from its own scientific, technical, cultural and institutional ecosystem into one operating frame. Research, evidence and execution are coordinated without flattening disciplinary authority.",
meta:["Paris","London","Dubai","Hangzhou","Shanghai","Hong Kong"],
sections:[
["01","What VOCE is","VOCE was built around a simple conviction: the major transformations of contemporary life no longer fit inside one discipline. Artificial intelligence affects work and responsibility. Digital environments reshape attention and relationships. Medicine is transformed by data, biomarkers and software. Culture and design preserve forms of intelligence that technical analysis alone cannot explain.","VOCE therefore works as a house of inquiry rather than a conventional media brand. It studies mechanisms, architectures and human consequences, then translates that work into research papers, courses, briefings, seminars and public-facing editorial formats.","Its ambition is not to comment on everything. It is to make a smaller number of difficult subjects unusually clear."],
["02","The intellectual architecture","VOCE connects fields that are usually separated: artificial intelligence and governance, neuroscience and psychology, health and medicine, digital environments and human behaviour, education and society, culture and heritage, technology, infrastructure and work.","The common thread is the relationship between systems and human agency. What does a technology allow? What does an institution delegate? What happens to attention, judgment, expertise, memory, language, trust or responsibility when an operating system changes?","This is why a VOCE analysis can begin with a technical protocol and end with a question of apprenticeship, childhood, care, cultural transmission or institutional legitimacy."],
["03","Research before posture","VOCE does not begin with a political, commercial or technological position and search for evidence that supports it. The method begins with the object: a study, architecture, regulation, infrastructure, clinical mechanism, platform behaviour, historical object or institutional decision.","The work then separates what is documented from what is inferred, distinguishes correlation from causality, and identifies methodological limits. The result is written to remain intelligible to a non-specialist without reducing the technical substance.","Formal research outputs are distinguished from editorial analysis. VOCE Research publishes work with persistent identifiers where appropriate; VOCE’s editorial corpus interprets recent evidence and systems for a wider audience."],
["04","A scientific committee inside the ecosystems","VOCE draws on a scientific committee and expert network whose members and contributors work inside the environments being analysed. The network brings together technology practitioners, psychiatrists, cultural actors, artists, people working with foundations and institutions, and experts exposed to different regional systems.","Paris and London offer institutional, financial, cultural and research depth. Dubai provides a Gulf vantage point where infrastructure, capital and technology adoption are moving quickly. Hangzhou, Shanghai and Hong Kong offer different Chinese perspectives on platforms, commerce, industry, finance, luxury, technology and cross-border systems.","The purpose of this geography is comparative intelligence. VOCE does not treat one market as the default model for the world."],
["05","Opera, philosophy and the VOCE method","Opera is not a decorative layer of the brand. It provides a method. Several voices can occupy the same scene without becoming the same voice. Evidence, clinical experience, technical architecture, institutional practice and culture can remain distinct before being interpreted together.","Italian philosophy offers another form of discipline. Vico asks what it means to understand what we build. Machiavelli asks how agency survives inside unstable systems. Croce asks how history is made present. Leopardi asks what happens inside the human mind when the world and desire exceed it.","VOCE uses these counterpoints to resist two simplifications: treating technology as destiny, and treating the human as an abstract moral slogan."],
["06","What VOCE produces","VOCE Research develops formal and applied research. The VOCE AI Governance Institute now connects four agent-assurance layers: Agent Infrastructure for architecture, Agent Conformance for evidence-based controls, ARGOS — AI Evaluation & Continuous Assurance for continuous re-evaluation, and Human Cognitive & Neuropsychology Assurance for attention, cognitive load, memory, decision fatigue and the quality of human oversight. COURS VOCE® and the editorial corpus extend that work across science, medicine, technology, culture, infrastructure and human behaviour.","The cognitive and neuropsychology layer is explicitly non-diagnostic: it is designed to assess human-system interaction and oversight quality, not to automate psychological diagnosis or replace qualified clinical practice. Seminars and institutional work deepen selected subjects with organisations, experts and cultural partners."],
["07","No one left unheard","The phrase predates the current expansion of VOCE, but it still defines the institution. “No one left unheard” does not mean that every claim is equivalent. It means that systems should be read with attention to the people, disciplines and consequences that are easiest to remove from the frame.","VOCE’s role is to preserve that plurality without abandoning standards of evidence. The voice matters precisely because it is confronted with facts, method and other voices."]
],
linksTitle:"Continue through VOCE",
links:[
["Research","How VOCE distinguishes formal research, applied research and editorial analysis.","/research"],
["Governance & Standards","How VOCE works, checks sources, handles limits, corrections and AI-assisted research.","/standards"],
["AI Governance","VOCE’s technical research pathway on institutional AI systems.","/governance"],
["Publications","Formal research outputs, DOI records and the wider editorial corpus.","/publications"]
]
},
fr:{
kicker:"À propos de VOCE",
title:"Une institution de recherche, de culture et d’orchestration des systèmes complexes.",
deck:"VOCE réunit les spécialistes de son propre écosystème scientifique, technique, culturel et institutionnel dans un même cadre opérationnel. Recherche, preuve et exécution sont coordonnées sans effacer l’autorité de chaque discipline.",
meta:["Paris","Londres","Dubaï","Hangzhou","Shanghai","Hong Kong"],
sections:[
["01","Ce qu’est VOCE","VOCE est née d’une conviction simple: les transformations majeures de la vie contemporaine ne tiennent plus dans une seule discipline. L’intelligence artificielle transforme le travail et la responsabilité. Les environnements numériques modifient l’attention et les relations. La médecine se transforme avec les données, les biomarqueurs et le logiciel. La culture et le design conservent des formes d’intelligence que l’analyse technique seule ne suffit pas à expliquer.","VOCE fonctionne donc comme une maison d’enquête plutôt que comme un média conventionnel. Elle étudie des mécanismes, des architectures et leurs conséquences humaines, puis transforme ce travail en recherches, cours, notes, séminaires et formats éditoriaux ouverts au public.","Son ambition n’est pas de commenter tout. Elle consiste à rendre un nombre plus limité de sujets difficiles exceptionnellement clairs."],
["02","L’architecture intellectuelle","VOCE relie des domaines habituellement séparés: intelligence artificielle et gouvernance, neurosciences et psychologie, santé et médecine, environnements numériques et comportement humain, éducation et société, culture et patrimoine, technologie, infrastructures et travail.","Le fil commun est la relation entre les systèmes et l’agentivité humaine. Que permet une technologie? Que délègue une institution? Que deviennent attention, jugement, expertise, mémoire, langage, confiance ou responsabilité lorsqu’un système opérationnel change?","C’est pourquoi une analyse VOCE peut commencer par un protocole technique et finir par une question d’apprentissage, d’enfance, de soin, de transmission culturelle ou de légitimité institutionnelle."],
["03","La recherche avant la posture","VOCE ne part pas d’une position politique, commerciale ou technologique pour chercher ensuite les éléments qui la confirment. La méthode part de l’objet: étude, architecture, réglementation, infrastructure, mécanisme clinique, comportement de plateforme, objet historique ou décision institutionnelle.","Le travail sépare ensuite ce qui est documenté de ce qui est inféré, distingue corrélation et causalité et rend visibles les limites méthodologiques. L’écriture doit rester intelligible à un non-spécialiste sans réduire la substance technique.","Les travaux de recherche formels sont distingués de l’analyse éditoriale. VOCE Research publie, lorsque cela est pertinent, avec identifiants persistants; le corpus éditorial VOCE interprète les données et les systèmes récents pour un public plus large."],
["04","Un comité scientifique au contact des écosystèmes","VOCE s’appuie sur un comité scientifique et un réseau d’experts dont les membres et contributeurs travaillent au sein des environnements étudiés. Le réseau croise praticiens de la technologie, psychiatres, acteurs culturels, artistes, personnes engagées auprès de fondations et d’institutions, ainsi que des experts exposés à des systèmes régionaux différents.","Paris et Londres apportent profondeur institutionnelle, financière, culturelle et scientifique. Dubaï offre un point d’observation du Golfe où infrastructures, capital et adoption technologique avancent rapidement. Hangzhou, Shanghai et Hong Kong donnent accès à des perspectives chinoises distinctes sur plateformes, commerce, industrie, finance, luxe, technologie et systèmes transfrontaliers.","Cette géographie sert une intelligence comparative. VOCE ne prend pas un seul marché pour modèle par défaut du monde."],
["05","L’opéra, la philosophie et la méthode VOCE","L’opéra n’est pas une couche décorative de la marque. Il fournit une méthode. Plusieurs voix peuvent occuper une même scène sans devenir une seule voix. Preuve scientifique, expérience clinique, architecture technique, pratique institutionnelle et culture peuvent rester distinctes avant d’être interprétées ensemble.","La philosophie italienne apporte une autre discipline. Vico interroge ce que signifie comprendre ce que nous construisons. Machiavel demande comment l’action demeure possible dans des systèmes instables. Croce rappelle que l’histoire se rend toujours présente. Leopardi explore ce qui se passe dans l’esprit lorsque le monde et le désir le débordent.","VOCE utilise ces contrepoints pour résister à deux simplifications: traiter la technologie comme un destin, ou traiter l’humain comme un slogan moral abstrait."],
["06","Ce que produit VOCE","VOCE Research développe recherche formelle et recherche appliquée. Le VOCE AI Governance Institute relie désormais quatre couches d’assurance agentique: Agent Infrastructure pour l’architecture, Agent Conformance pour les contrôles fondés sur les preuves, ARGOS — AI Evaluation & Continuous Assurance pour la réévaluation continue, puis Human Cognitive Assurance, consacrée à l’attention, la charge cognitive, la mémoire, la fatigue décisionnelle et la qualité de la supervision humaine. Les COURS VOCE® et le corpus éditorial prolongent ce travail dans la science, la médecine, la technologie, la culture, les infrastructures et le comportement humain.","La couche cognitive et neuropsychologique est explicitement non diagnostique: elle vise l’interaction humain-système et la qualité de la supervision, jamais l’automatisation d’un diagnostic psychologique ni le remplacement d’une pratique clinique qualifiée. Les séminaires et travaux institutionnels approfondissent certains sujets avec des organisations, des experts et des partenaires culturels."],
["07","No one left unheard","La formule précède l’élargissement actuel de VOCE, mais elle continue de définir l’institution. “No one left unheard” ne signifie pas que toutes les affirmations se valent. Cela signifie que les systèmes doivent être lus en tenant compte des personnes, disciplines et conséquences qu’il est le plus facile de faire disparaître du cadre.","Le rôle de VOCE est de préserver cette pluralité sans abandonner les standards de preuve. La voix compte précisément parce qu’elle est confrontée aux faits, à la méthode et aux autres voix."]
],
linksTitle:"Poursuivre dans VOCE",
links:[
["Research","Comment VOCE distingue recherche formelle, recherche appliquée et analyse éditoriale.","/research"],
["Gouvernance & standards","Comment VOCE travaille, vérifie ses sources, traite les limites, corrections et usages de l’IA.","/standards"],
["Gouvernance de l’IA","Le parcours technique VOCE consacré aux systèmes d’IA institutionnels.","/governance"],
["Publications","Travaux formels, DOI et corpus éditorial VOCE.","/publications"]
]
},
it:{
kicker:"Chi è VOCE",
title:"Un’istituzione di ricerca, cultura e orchestrazione dei sistemi complessi.",
deck:"VOCE riunisce gli specialisti del proprio ecosistema scientifico, tecnico, culturale e istituzionale in un unico quadro operativo. Ricerca, evidenza ed esecuzione vengono coordinate senza cancellare l’autorità di ciascuna disciplina.",
meta:["Parigi","Londra","Dubai","Hangzhou","Shanghai","Hong Kong"],
sections:[
["01","Che cos’è VOCE","VOCE nasce da una convinzione semplice: le grandi trasformazioni della vita contemporanea non rientrano più in una sola disciplina. L’intelligenza artificiale modifica lavoro e responsabilità. Gli ambienti digitali cambiano attenzione e relazioni. La medicina viene trasformata da dati, biomarcatori e software. Cultura e design conservano forme di intelligenza che l’analisi tecnica, da sola, non riesce a spiegare.","VOCE funziona quindi come una casa di indagine più che come un media convenzionale. Studia meccanismi, architetture e conseguenze umane, poi trasforma questo lavoro in ricerca, corsi, briefing, seminari e formati editoriali aperti al pubblico.","L’ambizione non è commentare tutto. È rendere eccezionalmente chiari un numero più limitato di temi difficili."],
["02","L’architettura intellettuale","VOCE collega campi normalmente separati: intelligenza artificiale e governance, neuroscienze e psicologia, salute e medicina, ambienti digitali e comportamento umano, educazione e società, cultura e patrimonio, tecnologia, infrastrutture e lavoro.","Il filo comune è il rapporto tra sistemi e capacità d’azione umana. Che cosa consente una tecnologia? Che cosa delega un’istituzione? Che cosa accade ad attenzione, giudizio, competenza, memoria, linguaggio, fiducia o responsabilità quando cambia un sistema operativo?","Per questo un’analisi VOCE può iniziare da un protocollo tecnico e terminare con una questione di apprendistato, infanzia, cura, trasmissione culturale o legittimità istituzionale."],
["03","La ricerca prima della postura","VOCE non parte da una posizione politica, commerciale o tecnologica per cercare poi le prove che la confermano. Il metodo parte dall’oggetto: studio, architettura, regolazione, infrastruttura, meccanismo clinico, comportamento di piattaforma, oggetto storico o decisione istituzionale.","Il lavoro separa ciò che è documentato da ciò che viene inferito, distingue correlazione e causalità e rende visibili i limiti metodologici. La scrittura deve restare comprensibile a un non specialista senza ridurre la sostanza tecnica.","I risultati di ricerca formali vengono distinti dall’analisi editoriale. VOCE Research pubblica, quando appropriato, con identificatori persistenti; il corpus editoriale VOCE interpreta evidenze e sistemi recenti per un pubblico più ampio."],
["04","Un comitato scientifico dentro gli ecosistemi","VOCE si appoggia a un comitato scientifico e a una rete di esperti i cui membri e contributori lavorano negli ambienti studiati. La rete riunisce professionisti della tecnologia, psichiatri, attori culturali, artisti, persone attive con fondazioni e istituzioni ed esperti esposti a differenti sistemi regionali.","Parigi e Londra portano profondità istituzionale, finanziaria, culturale e scientifica. Dubai offre un punto di osservazione del Golfo in cui infrastrutture, capitale e adozione tecnologica avanzano rapidamente. Hangzhou, Shanghai e Hong Kong offrono prospettive cinesi differenti su piattaforme, commercio, industria, finanza, lusso, tecnologia e sistemi transfrontalieri.","Questa geografia serve un’intelligenza comparativa. VOCE non assume un solo mercato come modello predefinito del mondo."],
["05","Opera, filosofia e metodo VOCE","L’opera non è uno strato decorativo del marchio. Offre un metodo. Più voci possono occupare la stessa scena senza diventare la stessa voce. Evidenza scientifica, esperienza clinica, architettura tecnica, pratica istituzionale e cultura possono restare distinte prima di essere interpretate insieme.","La filosofia italiana aggiunge un’altra disciplina. Vico interroga cosa significhi comprendere ciò che costruiamo. Machiavelli chiede come l’azione resti possibile dentro sistemi instabili. Croce ricorda come la storia si renda presente. Leopardi esplora ciò che accade nella mente quando mondo e desiderio la oltrepassano.","VOCE usa questi contrappunti per resistere a due semplificazioni: trattare la tecnologia come destino, o l’umano come slogan morale astratto."],
["06","Che cosa produce VOCE","VOCE Research sviluppa ricerca formale e applicata. Il VOCE AI Governance Institute collega ora quattro livelli di assurance agentica: Agent Infrastructure per l’architettura, Agent Conformance per i controlli basati su evidenze, ARGOS — AI Evaluation & Continuous Assurance per la rivalutazione continua, e Human Cognitive Assurance, dedicata ad attenzione, carico cognitivo, memoria, affaticamento decisionale e qualità della supervisione umana. I CORSI VOCE® e il corpus editoriale estendono questo lavoro a scienza, medicina, tecnologia, cultura, infrastrutture e comportamento umano.","Il livello cognitivo e neuropsicologico è esplicitamente non diagnostico: serve a valutare l’interazione uomo-sistema e la qualità della supervisione, non ad automatizzare diagnosi psicologiche né a sostituire una pratica clinica qualificata. Seminari e lavori istituzionali approfondiscono temi selezionati con organizzazioni, esperti e partner culturali."],
["07","No one left unheard","La formula precede l’attuale ampliamento di VOCE, ma continua a definire l’istituzione. “No one left unheard” non significa che tutte le affermazioni siano equivalenti. Significa che i sistemi devono essere letti prestando attenzione a persone, discipline e conseguenze che è più facile rimuovere dal quadro.","Il ruolo di VOCE è preservare questa pluralità senza abbandonare gli standard di evidenza. La voce conta proprio perché viene confrontata con fatti, metodo e altre voci."]
],
linksTitle:"Continuare dentro VOCE",
links:[
["Research","Come VOCE distingue ricerca formale, ricerca applicata e analisi editoriale.","/research"],
["Governance & standard","Come VOCE lavora, verifica le fonti, tratta limiti, correzioni e uso dell’IA.","/standards"],
["Governance dell’IA","Il percorso tecnico VOCE sui sistemi di IA istituzionali.","/governance"],
["Pubblicazioni","Ricerca formale, DOI e corpus editoriale VOCE.","/publications"]
]
}
},
standards:{
en:{kicker:"VOCE Standards · Institutional Orchestration",title:"Decision-grade evidence for systems that carry capital, authority and consequence.",deck:"VOCE operates as an institutional orchestration layer: specialists inside the VOCE ecosystem examine the same system from different disciplines, then align evidence, architecture, permissions, economics and human authority before a decision is made.",meta:["Evidence provenance","Architecture","Authority","Reversibility","Accountability"],sections:[
["01","Evidence provenance and time integrity","VOCE gives priority to primary or near-primary evidence: peer-reviewed research, official datasets, regulations, technical documentation, infrastructure specifications, audited disclosures, code repositories and first-party product documentation. Secondary reporting can identify a signal; it does not silently become the evidentiary base.","For fast-moving subjects, date is part of truth. Model capability, product availability, pricing, licensing, data residency, regulatory status and geographic access are treated as time-bound claims and re-verified before they support an institutional recommendation."],
["02","Decision-grade claims","A VOCE conclusion separates fact, interpretation, scenario and recommendation. Vendor claims are identified as vendor claims. Correlation is not promoted into causality. Missing public information remains missing. Material uncertainty is carried into the decision rather than edited out of the narrative.","The objective is not maximal caution. It is calibrated confidence: strong conclusions where the evidence stack is strong, bounded conclusions where the stack is incomplete, and explicit refusal to manufacture precision where none exists."],
["03","Specialists inside the institution","VOCE is not an external generalist standing between a client and its experts. Its operating model begins with specialist knowledge inside the VOCE scientific, technical, cultural and institutional ecosystem. Depending on the problem, legal, psychiatric, technological, cultural, financial, governance, infrastructure or design expertise can be brought into the same analytical frame from the outset.","External providers and additional specialists can then be added where required. They enter an architecture whose questions, evidence standards and decision rights are already defined rather than becoming the architecture themselves."],
["04","The orchestration standard","VOCE coordinates systems in which no single discipline is sufficient. The work maps dependencies between people, models, software, data, contracts, incentives, controls and institutions, then identifies where authority actually sits. The output is an operating score: what must happen, in what order, under whose responsibility and with which evidence.","This matters when an apparently technical choice changes legal exposure, workforce design, cultural sovereignty, balance-sheet risk or institutional trust. Orchestration is the discipline of keeping those consequences visible at the same time."],
["05","Authority, permissions and segregation of duties","Any operational architecture must identify who can see, decide, execute, approve, override and stop. For agents and automated systems, this includes tool permissions, data scopes, transaction limits, approval thresholds, exception paths and revocation mechanisms. For human organisations, it includes decision rights and segregation of duties.","Human oversight is meaningful only when it is attached to an identifiable accountable owner and an executable control. A committee without authority, a log nobody reviews or an approval that can be bypassed is not governance."],
["06","Vendor neutrality, concentration risk and reversibility","VOCE Applied and VOCE Solutions begin with the function to be performed and the risk to be controlled, not with a preferred supplier. Proprietary cloud, specialist SaaS, open-weight models and self-hosted systems are compared as different architectures with different economics and control surfaces.","The assessment includes switching cost, data portability, identity dependencies, API lock-in, licensing, model substitutability, regional availability and exit conditions. A system that performs well but cannot be replaced without disproportionate disruption creates strategic concentration risk."],
["07","Economics, optionality and institutional consequence","Technical efficiency is not evaluated in isolation. VOCE follows the change into operating cost, staffing structure, apprenticeship, procurement exposure, insurance, compliance burden, capital allocation and institutional optionality when these effects are material.","A lower unit cost can destroy resilience; a premium architecture can preserve strategic freedom. The relevant comparison is therefore not simply price or benchmark performance, but the risk-adjusted operating position the institution acquires after deployment."],
["08","Why opera belongs to the method","Opera is not VOCE’s decorative vocabulary. It is a model for governing complexity. Distinct voices retain their register, authority and timing while contributing to one intelligible work. The score makes relationships explicit without reducing the orchestra to one instrument.","VOCE works the same way. Its specialists do not dissolve into a generic consultancy voice. Law remains law, psychiatry remains psychiatry, engineering remains engineering, culture remains culture. The orchestration layer aligns their entrances, dependencies and consequences so a board can understand the system as a whole."],
["09","Traceability, AI use and continuous assurance","VOCE may use AI for retrieval, comparison, drafting, translation, coding, classification and workflow support. Model output is never treated as primary evidence. Material claims must remain traceable to identifiable sources, and consequential actions must have an accountable operating owner.","Where systems evolve continuously, assurance must also evolve. Changes in models, permissions, data sources, vendors or regulations can invalidate a previous conclusion. Versioning, review dates, audit trails and re-evaluation are therefore part of the standard, not administrative afterthoughts."],
["10","Independence, conflicts and professional responsibility","VOCE’s research and editorial independence must remain distinguishable from commercial, institutional or philanthropic relationships. A material relationship affecting a publication, registry entry or project should be disclosed. Partners, suppliers and funders do not acquire editorial or analytical control over the conclusion.","VOCE can research, compare, design, coordinate and govern complex work through specialists within its ecosystem. Acts that legally require a licensed clinician, lawyer, statutory auditor, regulated financial professional or other accountable practitioner remain attached to the qualified individual responsible for them."]
],linksTitle:"Institutional pathways",links:[["About VOCE","The institution, its specialist ecosystem and orchestration model.","/about"],["VOCE Applied","From evidence to operating architecture and execution.","/applied"],["VOCE Atlas","Documented relationships and evidence paths across the VOCE corpus.","/atlas"],["Agent Infrastructure Reference","European reference architecture for API, MCP, A2A, identity, authorization and agent assurance.","/agent-infrastructure"],["Agent Conformance","Evidence-based assessment of controls, authority and operational proof.","/agent-conformance"],["AI Governance","Model-to-system governance, agents, permissions and continuous assurance.","/governance"]]},
fr:{kicker:"Standards VOCE · orchestration institutionnelle",title:"Des preuves de niveau décisionnel pour les systèmes qui engagent capital, autorité et responsabilité.",deck:"VOCE agit comme une couche d’orchestration institutionnelle: les spécialistes présents dans l’écosystème VOCE examinent un même système depuis plusieurs disciplines, puis alignent preuves, architecture, permissions, économie et autorité humaine avant la décision.",meta:["Provenance des preuves","Architecture","Autorité","Réversibilité","Responsabilité"],sections:[
["01","Provenance des preuves et intégrité temporelle","VOCE privilégie les sources primaires ou proches des sources primaires: recherche évaluée par les pairs, données officielles, réglementations, documentation technique, spécifications d’infrastructure, publications auditées, dépôts de code et documentation produit de première partie. Une source secondaire peut révéler un signal; elle ne devient pas silencieusement la base probante.","Pour les sujets rapides, la date fait partie de la vérité. Capacité d’un modèle, disponibilité d’un produit, prix, licence, résidence des données, statut réglementaire et accès géographique sont traités comme des affirmations datées et revérifiés avant d’étayer une recommandation institutionnelle."],
["02","Affirmations de niveau décisionnel","Une conclusion VOCE sépare fait, interprétation, scénario et recommandation. Une affirmation fournisseur reste identifiée comme telle. Une corrélation n’est pas transformée en causalité. Une information publique absente reste absente. L’incertitude matérielle entre dans la décision au lieu d’être supprimée du récit.","L’objectif n’est pas la prudence maximale. Il est la confiance calibrée: conclusions fortes lorsque la chaîne de preuves est forte, conclusions bornées lorsque la preuve est incomplète, refus explicite de fabriquer une précision inexistante."],
["03","Des spécialistes au sein de l’institution","VOCE n’est pas un généraliste extérieur placé entre une organisation et ses experts. Son modèle commence par les expertises présentes dans son propre écosystème scientifique, technique, culturel et institutionnel. Selon le problème, droit, psychiatrie, technologie, culture, finance, gouvernance, infrastructures ou design peuvent être réunis dès l’origine dans le même cadre d’analyse.","Prestataires et spécialistes extérieurs peuvent ensuite être ajoutés lorsque nécessaire. Ils entrent dans une architecture dont les questions, les standards de preuve et les droits de décision sont déjà définis; ils ne deviennent pas eux-mêmes l’architecture."],
["04","Le standard d’orchestration","VOCE coordonne des systèmes dans lesquels aucune discipline ne suffit à elle seule. Le travail cartographie les dépendances entre personnes, modèles, logiciels, données, contrats, incitations, contrôles et institutions, puis identifie où se situe réellement l’autorité. Le livrable devient une partition opérationnelle: ce qui doit se produire, dans quel ordre, sous quelle responsabilité et avec quelle preuve.","Cette lecture est décisive lorsqu’un choix apparemment technique modifie l’exposition juridique, la structure du travail, la souveraineté culturelle, le risque de bilan ou la confiance institutionnelle. Orchestrer consiste à rendre ces conséquences simultanément visibles."],
["05","Autorité, permissions et séparation des fonctions","Toute architecture opérationnelle doit identifier qui peut voir, décider, exécuter, approuver, déroger et arrêter. Pour les agents et systèmes automatisés, cela inclut permissions d’outils, périmètres de données, limites transactionnelles, seuils d’approbation, voies d’exception et mécanismes de révocation. Pour les organisations humaines, cela inclut droits de décision et séparation des fonctions.","La supervision humaine n’a de sens que si elle est rattachée à un responsable identifiable et à un contrôle exécutable. Un comité sans autorité, un journal que personne ne relit ou une validation contournable ne constituent pas une gouvernance."],
["06","Neutralité fournisseur, concentration et réversibilité","VOCE Applied et VOCE Solutions partent de la fonction à accomplir et du risque à maîtriser, jamais d’un fournisseur à privilégier. Cloud propriétaire, SaaS métier, modèles open-weight et systèmes auto-hébergés sont comparés comme des architectures différentes, avec des économies et des surfaces de contrôle différentes.","L’analyse inclut coût de changement, portabilité des données, dépendances d’identité, verrouillage API, licences, substituabilité des modèles, disponibilité régionale et conditions de sortie. Un système performant mais impossible à remplacer sans rupture disproportionnée crée un risque stratégique de concentration."],
["07","Économie, optionalité et conséquence institutionnelle","L’efficacité technique n’est pas évaluée isolément. VOCE suit le changement jusque dans les coûts d’exploitation, la structure des effectifs, l’apprentissage, l’exposition achats, l’assurance, la charge de conformité, l’allocation du capital et l’optionalité institutionnelle lorsque ces effets sont matériels.","Un coût unitaire plus faible peut dégrader la résilience; une architecture plus chère peut préserver une liberté stratégique. La comparaison pertinente ne porte donc pas seulement sur le prix ou le benchmark, mais sur la position opérationnelle ajustée du risque que l’institution acquiert après déploiement."],
["08","Pourquoi l’opéra appartient à la méthode","L’opéra n’est pas le vocabulaire décoratif de VOCE. Il constitue un modèle de gouvernement de la complexité. Des voix distinctes conservent leur registre, leur autorité et leur temporalité tout en contribuant à une œuvre intelligible. La partition explicite les relations sans réduire l’orchestre à un seul instrument.","VOCE fonctionne de la même manière. Ses spécialistes ne se dissolvent pas dans une voix générique de conseil. Le droit reste le droit, la psychiatrie reste la psychiatrie, l’ingénierie reste l’ingénierie, la culture reste la culture. La couche d’orchestration aligne leurs entrées, leurs dépendances et leurs conséquences pour qu’un board puisse comprendre le système dans son ensemble."],
["09","Traçabilité, usage de l’IA et assurance continue","VOCE peut utiliser l’IA pour la recherche documentaire, la comparaison, la rédaction, la traduction, le code, la classification et les flux de travail. Une sortie de modèle n’est jamais traitée comme preuve primaire. Toute affirmation matérielle doit rester traçable vers une source identifiable et toute action conséquente doit avoir un responsable opérationnel.","Lorsque les systèmes évoluent en continu, l’assurance doit évoluer avec eux. Un changement de modèle, de permission, de source de données, de fournisseur ou de réglementation peut invalider une conclusion précédente. Versioning, dates de revue, traces d’audit et réévaluation font donc partie du standard."],
["10","Indépendance, conflits et responsabilité professionnelle","L’indépendance scientifique et éditoriale de VOCE doit rester distinguable de ses relations commerciales, institutionnelles ou philanthropiques. Toute relation matérielle affectant une publication, une entrée du registre ou un projet doit être signalée. Partenaires, fournisseurs et financeurs n’acquièrent aucun contrôle sur la conclusion.","VOCE peut rechercher, comparer, concevoir, coordonner et gouverner des travaux complexes grâce aux spécialistes présents dans son écosystème. Les actes qui exigent légalement un médecin, un avocat, un commissaire aux comptes, un professionnel financier réglementé ou un autre praticien responsable restent attachés à la personne qualifiée qui en assume la responsabilité."]
],linksTitle:"Parcours institutionnels",links:[["À propos de VOCE","L’institution, son écosystème de spécialistes et son modèle d’orchestration.","/about"],["VOCE Applied","De la preuve à l’architecture opérationnelle et à l’exécution.","/applied"],["VOCE Atlas","Relations documentées et chemins de preuve dans le corpus VOCE.","/atlas"],["Référence infrastructures agents","Architecture européenne pour API, MCP, A2A, identité, autorisation et assurance agentique.","/fr/agent-infrastructure"],["Agent Conformance","Évaluation par la preuve des contrôles, de l’autorité et de l’exécution réelle.","/fr/agent-conformance"],["Gouvernance de l’IA","Du modèle au système: agents, permissions et assurance continue.","/governance"]]},
it:{kicker:"Standard VOCE · orchestrazione istituzionale",title:"Evidenze di livello decisionale per sistemi che impegnano capitale, autorità e responsabilità.",deck:"VOCE opera come livello di orchestrazione istituzionale: gli specialisti presenti nell’ecosistema VOCE esaminano lo stesso sistema da discipline diverse, poi allineano evidenze, architettura, permessi, economia e autorità umana prima della decisione.",meta:["Provenienza delle evidenze","Architettura","Autorità","Reversibilità","Responsabilità"],sections:[
["01","Provenienza delle evidenze e integrità temporale","VOCE privilegia fonti primarie o prossime alle primarie: ricerca peer-reviewed, dati ufficiali, regolamentazioni, documentazione tecnica, specifiche infrastrutturali, disclosure sottoposte ad audit, repository di codice e documentazione di prima parte. Una fonte secondaria può individuare un segnale; non diventa silenziosamente la base probatoria.","Nei temi a rapida evoluzione, la data è parte della verità. Capacità del modello, disponibilità del prodotto, prezzo, licenza, data residency, stato regolamentare e accesso geografico sono trattati come affermazioni temporali e verificati nuovamente prima di sostenere una raccomandazione istituzionale."],
["02","Affermazioni di livello decisionale","Una conclusione VOCE separa fatto, interpretazione, scenario e raccomandazione. Le affermazioni dei vendor restano identificate come tali. La correlazione non viene elevata a causalità. Le informazioni pubbliche mancanti restano mancanti. L’incertezza materiale entra nella decisione invece di essere eliminata dalla narrazione.","L’obiettivo non è la cautela massima. È una fiducia calibrata: conclusioni forti quando la catena di evidenze è forte, conclusioni limitate quando è incompleta, rifiuto esplicito di fabbricare precisione dove non esiste."],
["03","Specialisti dentro l’istituzione","VOCE non è un generalista esterno posto tra un’organizzazione e i suoi esperti. Il suo modello operativo parte dalle competenze presenti nel proprio ecosistema scientifico, tecnico, culturale e istituzionale. In funzione del problema, diritto, psichiatria, tecnologia, cultura, finanza, governance, infrastrutture o design possono entrare nello stesso quadro analitico fin dall’inizio.","Fornitori e specialisti esterni possono poi essere aggiunti quando necessario. Entrano in un’architettura le cui domande, standard di evidenza e diritti decisionali sono già definiti; non diventano essi stessi l’architettura."],
["04","Lo standard di orchestrazione","VOCE coordina sistemi in cui nessuna disciplina è sufficiente da sola. Il lavoro mappa dipendenze tra persone, modelli, software, dati, contratti, incentivi, controlli e istituzioni, poi identifica dove risiede realmente l’autorità. L’output diventa una partitura operativa: cosa deve accadere, in quale ordine, sotto quale responsabilità e con quale evidenza.","Questo conta quando una scelta apparentemente tecnica modifica esposizione legale, struttura del lavoro, sovranità culturale, rischio di bilancio o fiducia istituzionale. Orchestrare significa mantenere visibili queste conseguenze nello stesso momento."],
["05","Autorità, permessi e segregazione dei compiti","Ogni architettura operativa deve identificare chi può vedere, decidere, eseguire, approvare, derogare e fermare. Per agenti e sistemi automatizzati ciò include permessi degli strumenti, ambiti dei dati, limiti transazionali, soglie di approvazione, percorsi di eccezione e meccanismi di revoca. Per le organizzazioni umane include diritti decisionali e segregazione dei compiti.","La supervisione umana ha senso solo se collegata a un responsabile identificabile e a un controllo realmente eseguibile. Un comitato senza autorità, un log che nessuno legge o un’approvazione aggirabile non costituiscono governance."],
["06","Neutralità del vendor, concentrazione e reversibilità","VOCE Applied e VOCE Solutions partono dalla funzione da svolgere e dal rischio da controllare, non da un fornitore preferito. Cloud proprietario, SaaS verticali, modelli open-weight e sistemi self-hosted sono confrontati come architetture diverse con economie e superfici di controllo diverse.","L’analisi comprende switching cost, portabilità dei dati, dipendenze di identità, lock-in API, licenze, sostituibilità dei modelli, disponibilità regionale e condizioni di uscita. Un sistema performante ma non sostituibile senza discontinuità sproporzionata crea rischio strategico di concentrazione."],
["07","Economia, optionalità e conseguenza istituzionale","L’efficienza tecnica non viene valutata in isolamento. VOCE segue il cambiamento nei costi operativi, struttura del personale, apprendistato, esposizione procurement, assicurazioni, carico di compliance, allocazione del capitale e optionalità istituzionale quando questi effetti sono materiali.","Un costo unitario inferiore può ridurre la resilienza; un’architettura più costosa può preservare libertà strategica. Il confronto rilevante non è quindi soltanto prezzo o benchmark, ma la posizione operativa corretta per il rischio acquisita dall’istituzione dopo il deployment."],
["08","Perché l’opera appartiene al metodo","L’opera non è il vocabolario decorativo di VOCE. È un modello di governo della complessità. Voci distinte conservano registro, autorità e tempo mentre contribuiscono a un’opera intelligibile. La partitura rende esplicite le relazioni senza ridurre l’orchestra a un solo strumento.","VOCE funziona allo stesso modo. I suoi specialisti non si dissolvono in una voce generica di consulenza. Il diritto resta diritto, la psichiatria resta psichiatria, l’ingegneria resta ingegneria, la cultura resta cultura. L’orchestrazione allinea ingressi, dipendenze e conseguenze affinché un board possa comprendere il sistema nel suo insieme."],
["09","Tracciabilità, uso dell’IA e continuous assurance","VOCE può usare l’IA per retrieval, confronto, redazione, traduzione, coding, classificazione e workflow. L’output di un modello non è mai trattato come evidenza primaria. Le affermazioni materiali devono restare tracciabili a fonti identificabili e le azioni rilevanti devono avere un responsabile operativo.","Quando i sistemi evolvono continuamente, anche l’assurance deve evolvere. Cambi di modello, permessi, fonti dati, vendor o regolamentazione possono invalidare una conclusione precedente. Versioning, date di revisione, audit trail e rivalutazione fanno quindi parte dello standard."],
["10","Indipendenza, conflitti e responsabilità professionale","L’indipendenza scientifica ed editoriale di VOCE deve restare distinguibile da relazioni commerciali, istituzionali o filantropiche. Ogni relazione materiale che incide su una pubblicazione, una voce del registro o un progetto deve essere dichiarata. Partner, fornitori e finanziatori non acquisiscono controllo sulla conclusione.","VOCE può ricercare, confrontare, progettare, coordinare e governare lavori complessi attraverso gli specialisti presenti nel proprio ecosistema. Gli atti che richiedono legalmente un medico, un avvocato, un revisore legale, un professionista finanziario regolamentato o altro soggetto responsabile restano attribuiti alla persona qualificata che ne assume la responsabilità."]
],linksTitle:"Percorsi istituzionali",links:[["Chi è VOCE","L’istituzione, il suo ecosistema di specialisti e il modello di orchestrazione.","/about"],["VOCE Applied","Dall’evidenza all’architettura operativa e all’esecuzione.","/applied"],["VOCE Atlas","Relazioni documentate e percorsi di evidenza nel corpus VOCE.","/atlas"],["Riferimento infrastruttura agenti","Architettura europea per API, MCP, A2A, identità, autorizzazione e assurance agentica.","/it/agent-infrastructure"],["Agent Conformance","Assessment evidence-based di controlli, autorità ed esecuzione reale.","/it/agent-conformance"],["Governance dell’IA","Dal modello al sistema: agenti, permessi e continuous assurance.","/governance"]]}
},
research:{
en:{kicker:"VOCE Research",title:"Research that moves from mechanism to human consequence.",deck:"VOCE distinguishes formal research, applied research and editorial intelligence while allowing them to inform one another.",meta:["Digital environments","AI & work","Health","Culture","Human behaviour"],sections:[
["01","Formal research","Formal research outputs use stable authorship, references, versioning and persistent identifiers where appropriate. Current work includes parental technoference and early language development, and the relationship between continuous digital stimulation and inner thinking.","The purpose is not volume. It is to create a small body of work whose method and claims can be inspected."],
["02","Applied research","Applied research follows mechanisms into operating environments. In AI governance, that means moving beyond model benchmarks to permissions, agents, RAG, tools, security, observability, FinOps and human accountability. In work, it means examining how agents change task architecture, productivity, apprenticeship and expertise.","In health and human behaviour, it means connecting biomarkers, diagnostics, attention, memory, relationships, platform design and lived experience without confusing public analysis with clinical care."],
["03","Editorial intelligence","VOCE’s editorial work is a research interface. It translates recent studies, technical systems, infrastructures and institutional changes into compact analysis without turning them into simplified news.","The recurring editorial test is: “I knew the subject, but not this.” The value lies in exposing a mechanism or detail that changes the reader’s mental model."],
["04","COURS VOCE®","COURS VOCE® is the explanatory layer. A course isolates one mechanism, defines the architecture, names the relevant metrics or controls, and shows how the subject connects to a wider system.","The format is deliberately compact. It is designed to be useful to readers who need more than a headline but less than a full academic paper."],
["05","Research geography","VOCE’s research is informed by different operating ecosystems. Europe provides dense regulatory and institutional contexts. Dubai provides a Gulf perspective shaped by infrastructure and rapid adoption. Hangzhou, Shanghai and Hong Kong expose different Chinese technology, commercial, industrial and financial systems.","Comparison is used to test assumptions, not to manufacture superficial internationalism."],
["06","Research agenda","The current agenda spans AI governance, sovereignty and orchestration, light workforce, technoference, cognition, attention, memory, health and medicine, education, culture, heritage, infrastructure and the changing relationship between people and machines.","These are not independent verticals. VOCE treats them as interacting layers of one contemporary system."]
],linksTitle:"Explore the research",links:[["AI Governance","Agents, RAG, permissions, orchestration, security and accountability.","/governance"],["Sovereignty","Open models, cognitive supply chains and strategic switching capacity.","/sovereignty"],["Light workforce","Automation, productivity, apprenticeship and expertise.","/light-workforce"],["Technoference","Attention, language, memory, relationships and digital interruption.","/technoference"]]},
fr:{kicker:"VOCE Research",title:"Une recherche qui va du mécanisme jusqu’à la conséquence humaine.",deck:"VOCE distingue recherche formelle, recherche appliquée et intelligence éditoriale tout en les laissant s’informer mutuellement.",meta:["Environnements numériques","IA & travail","Santé","Culture","Comportement humain"],sections:[
["01","Recherche formelle","Les travaux formels reposent sur une attribution stable, des références, un suivi des versions et des identifiants persistants lorsque cela est pertinent. Les travaux actuels incluent la technoference parentale et le développement précoce du langage, ainsi que la relation entre stimulation numérique continue et pensée intérieure.","L’objectif n’est pas le volume. Il s’agit de constituer un corpus limité dont la méthode et les affirmations peuvent être examinées."],
["02","Recherche appliquée","La recherche appliquée suit les mécanismes jusque dans les environnements opérationnels. En gouvernance de l’IA, cela signifie dépasser les benchmarks de modèles pour étudier permissions, agents, RAG, outils, sécurité, observabilité, FinOps et responsabilité humaine. Dans le travail, cela signifie analyser comment les agents transforment architecture des tâches, productivité, apprentissage et expertise.","En santé et comportement humain, cela signifie relier biomarqueurs, diagnostic, attention, mémoire, relations, design des plateformes et expérience vécue sans confondre analyse publique et prise en charge clinique."],
["03","Intelligence éditoriale","Le travail éditorial VOCE est une interface de recherche. Il traduit études récentes, systèmes techniques, infrastructures et changements institutionnels en analyses compactes sans les réduire à de l’actualité simplifiée.","Le test éditorial récurrent est: “je connaissais le sujet, mais pas ça”. La valeur vient du mécanisme ou du détail qui modifie le modèle mental du lecteur."],
["04","COURS VOCE®","COURS VOCE® constitue la couche explicative. Un cours isole un mécanisme, définit l’architecture, nomme les métriques ou contrôles pertinents et montre comment le sujet s’insère dans un système plus large.","Le format est volontairement compact. Il est pensé pour des lecteurs qui ont besoin de davantage qu’un titre, mais de moins qu’un article académique complet."],
["05","Géographie de recherche","La recherche VOCE est nourrie par plusieurs écosystèmes opérationnels. L’Europe apporte des contextes réglementaires et institutionnels denses. Dubaï apporte une perspective du Golfe façonnée par l’infrastructure et l’adoption rapide. Hangzhou, Shanghai et Hong Kong exposent des systèmes chinois technologiques, commerciaux, industriels et financiers différents.","La comparaison sert à tester des hypothèses, pas à fabriquer un internationalisme superficiel."],
["06","Agenda de recherche","L’agenda actuel couvre gouvernance de l’IA, souveraineté et orchestration, light workforce, technoference, cognition, attention, mémoire, santé et médecine, éducation, culture, patrimoine, infrastructures et évolution de la relation entre personnes et machines.","Ces sujets ne sont pas des verticales indépendantes. VOCE les traite comme les couches interactives d’un même système contemporain."]
],linksTitle:"Explorer la recherche",links:[["Gouvernance de l’IA","Agents, RAG, permissions, orchestration, sécurité et responsabilité.","/governance"],["Souveraineté","Modèles ouverts, chaîne cognitive et capacité stratégique de changement.","/sovereignty"],["Light workforce","Automatisation, productivité, apprentissage et expertise.","/light-workforce"],["Technoference","Attention, langage, mémoire, relations et interruption numérique.","/technoference"]]},
it:{kicker:"VOCE Research",title:"Una ricerca che va dal meccanismo alla conseguenza umana.",deck:"VOCE distingue ricerca formale, ricerca applicata e intelligence editoriale lasciando che si informino reciprocamente.",meta:["Ambienti digitali","IA & lavoro","Salute","Cultura","Comportamento umano"],sections:[
["01","Ricerca formale","I risultati formali utilizzano attribuzione stabile, riferimenti, versioning e identificatori persistenti quando appropriato. I lavori attuali includono technoference parentale e sviluppo precoce del linguaggio, e la relazione tra stimolazione digitale continua e pensiero interiore.","L’obiettivo non è il volume. È creare un corpus limitato in cui metodo e affermazioni possano essere esaminati."],
["02","Ricerca applicata","La ricerca applicata segue i meccanismi dentro gli ambienti operativi. Nella governance dell’IA significa andare oltre i benchmark dei modelli per studiare permessi, agenti, RAG, strumenti, sicurezza, osservabilità, FinOps e responsabilità umana. Nel lavoro significa osservare come gli agenti cambiano architettura dei compiti, produttività, apprendistato e competenza.","In salute e comportamento umano significa collegare biomarcatori, diagnosi, attenzione, memoria, relazioni, design delle piattaforme ed esperienza vissuta senza confondere analisi pubblica e cura clinica."],
["03","Intelligence editoriale","Il lavoro editoriale VOCE è un’interfaccia di ricerca. Traduce studi recenti, sistemi tecnici, infrastrutture e cambiamenti istituzionali in analisi compatte senza ridurli a notizie semplificate.","Il test editoriale ricorrente è: “conoscevo l’argomento, ma non questo”. Il valore sta nel meccanismo o dettaglio che cambia il modello mentale del lettore."],
["04","CORSI VOCE®","CORSI VOCE® è il livello esplicativo. Un corso isola un meccanismo, definisce l’architettura, nomina metriche o controlli rilevanti e mostra come il tema si collega a un sistema più ampio.","Il formato è volutamente compatto. È pensato per lettori che hanno bisogno di più di un titolo ma meno di un paper accademico completo."],
["05","Geografia della ricerca","La ricerca VOCE è informata da diversi ecosistemi operativi. L’Europa offre contesti regolamentari e istituzionali densi. Dubai offre una prospettiva del Golfo plasmata da infrastrutture e adozione rapida. Hangzhou, Shanghai e Hong Kong espongono sistemi cinesi tecnologici, commerciali, industriali e finanziari differenti.","Il confronto serve a testare ipotesi, non a produrre un internazionalismo superficiale."],
["06","Agenda di ricerca","L’agenda attuale comprende governance dell’IA, sovranità e orchestrazione, light workforce, technoference, cognizione, attenzione, memoria, salute e medicina, educazione, cultura, patrimonio, infrastrutture e cambiamento del rapporto tra persone e macchine.","Non sono verticali indipendenti. VOCE li tratta come livelli interagenti di un unico sistema contemporaneo."]
],linksTitle:"Esplora la ricerca",links:[["Governance dell’IA","Agenti, RAG, permessi, orchestrazione, sicurezza e responsabilità.","/governance"],["Sovranità","Modelli aperti, catena cognitiva e capacità strategica di cambiamento.","/sovereignty"],["Light workforce","Automazione, produttività, apprendistato e competenza.","/light-workforce"],["Technoference","Attenzione, linguaggio, memoria, relazioni e interruzione digitale.","/technoference"]]}
},
publications:{
en:{kicker:"Publications",title:"A corpus designed to remain inspectable.",deck:"VOCE separates formal research outputs from editorial analysis while giving both a clear place in the institution.",meta:["DOI","Research","Courses","Editorial series"],sections:[
["01","Formal research outputs","VOCE Research publishes work with stable references and persistent identifiers where appropriate. Two current outputs are listed below.","When digital stimulation disrupts inner thinking · DOI 10.5281/zenodo.19189281","How parental technoference affects early language development · DOI 10.5281/zenodo.19114381"],
["02","Editorial corpus","VOCE’s editorial corpus spans artificial intelligence, health, neuroscience, psychology, technology, infrastructure, culture, logistics, medicine, education and human behaviour. These texts are not presented as peer-reviewed papers unless they are formal research outputs.","Their function is interpretive: identify an overlooked mechanism, explain why it matters and preserve the chain back to the source."],
["03","COURS VOCE®","The course format converts a difficult subject into an expert explanatory unit: mechanism, architecture, vocabulary, controls, metrics and implications.","Topics increasingly include AI systems, governance, agents, RAG, model routing, sovereignty, infrastructure, workforce transformation and the cognitive effects of digital environments."],
["04","Versions and archive","VOCE is building a canonical institutional archive so that research outputs, courses and major editorial texts can be located by subject, date, source and version.","The website is intended to become that source of record rather than leaving the institution dependent on social platforms."]
],linksTitle:"Direct access",links:[["Digital stimulation & inner thinking","Open DOI record.","/research/introspective-technoference"],["Parental technoference & language","Open DOI record.","/research/parental-technoference-language-development"],["VOCE Research","Research architecture and current agenda.","/research"],["LinkedIn","Current public editorial stream.","https://fr.linkedin.com/in/voce-association-0030763b6"]]},
fr:{kicker:"Publications",title:"Un corpus conçu pour rester vérifiable.",deck:"VOCE sépare les travaux de recherche formels de l’analyse éditoriale tout en donnant à chacun une place claire dans l’institution.",meta:["DOI","Recherche","Cours","Séries éditoriales"],sections:[
["01","Travaux de recherche formels","VOCE Research publie des travaux avec références stables et identifiants persistants lorsque cela est pertinent. Deux travaux actuels sont présentés ci-dessous.","Quand la stimulation numérique perturbe la pensée intérieure · DOI 10.5281/zenodo.19189281","Comment la technoference parentale affecte le développement précoce du langage · DOI 10.5281/zenodo.19114381"],
["02","Corpus éditorial","Le corpus éditorial VOCE traverse intelligence artificielle, santé, neurosciences, psychologie, technologie, infrastructures, culture, logistique, médecine, éducation et comportement humain. Ces textes ne sont pas présentés comme des publications évaluées par les pairs lorsqu’ils ne relèvent pas de la recherche formelle.","Leur fonction est interprétative: identifier un mécanisme négligé, expliquer pourquoi il compte et préserver la chaîne qui ramène à la source."],
["03","COURS VOCE®","Le format COURS VOCE® transforme un sujet difficile en unité explicative experte: mécanisme, architecture, vocabulaire, contrôles, métriques et implications.","Les thèmes couvrent de plus en plus les systèmes d’IA, la gouvernance, les agents, le RAG, le routage des modèles, la souveraineté, les infrastructures, la transformation du travail et les effets cognitifs des environnements numériques."],
["04","Versions et archive","VOCE construit une archive institutionnelle canonique afin que recherches, cours et textes éditoriaux majeurs puissent être retrouvés par sujet, date, source et version.","Le site a vocation à devenir cette source de référence plutôt que de laisser l’institution dépendre des plateformes sociales."]
],linksTitle:"Accès direct",links:[["Stimulation numérique & pensée intérieure","Ouvrir le DOI.","/research/introspective-technoference"],["Technoference parentale & langage","Ouvrir le DOI.","/research/parental-technoference-language-development"],["VOCE Research","Architecture de recherche et agenda actuel.","/research"],["LinkedIn","Flux éditorial public actuel.","https://fr.linkedin.com/in/voce-association-0030763b6"]]},
it:{kicker:"Pubblicazioni",title:"Un corpus progettato per restare verificabile.",deck:"VOCE separa i risultati formali di ricerca dall’analisi editoriale dando a entrambi un posto chiaro nell’istituzione.",meta:["DOI","Ricerca","Corsi","Serie editoriali"],sections:[
["01","Risultati formali di ricerca","VOCE Research pubblica lavori con riferimenti stabili e identificatori persistenti quando appropriato. Due risultati attuali sono indicati qui sotto.","Quando la stimolazione digitale interrompe il pensiero interiore · DOI 10.5281/zenodo.19189281","Come la technoference parentale influenza lo sviluppo precoce del linguaggio · DOI 10.5281/zenodo.19114381"],
["02","Corpus editoriale","Il corpus editoriale VOCE attraversa intelligenza artificiale, salute, neuroscienze, psicologia, tecnologia, infrastrutture, cultura, logistica, medicina, educazione e comportamento umano. Questi testi non vengono presentati come paper peer-reviewed quando non sono risultati formali di ricerca.","La loro funzione è interpretativa: identificare un meccanismo trascurato, spiegare perché conta e preservare la catena che ritorna alla fonte."],
["03","CORSI VOCE®","Il formato CORSI VOCE® trasforma un tema difficile in un’unità esplicativa esperta: meccanismo, architettura, vocabolario, controlli, metriche e implicazioni.","I temi includono sempre più sistemi IA, governance, agenti, RAG, routing dei modelli, sovranità, infrastrutture, trasformazione del lavoro ed effetti cognitivi degli ambienti digitali."],
["04","Versioni e archivio","VOCE sta costruendo un archivio istituzionale canonico affinché ricerca, corsi e principali testi editoriali possano essere ritrovati per tema, data, fonte e versione.","Il sito è destinato a diventare questa fonte di riferimento invece di lasciare l’istituzione dipendente dalle piattaforme sociali."]
],linksTitle:"Accesso diretto",links:[["Stimolazione digitale & pensiero interiore","Apri il DOI.","/research/introspective-technoference"],["Technoference parentale & linguaggio","Apri il DOI.","/research/parental-technoference-language-development"],["VOCE Research","Architettura di ricerca e agenda attuale.","/research"],["LinkedIn","Flusso editoriale pubblico attuale.","https://fr.linkedin.com/in/voce-association-0030763b6"]]}
},
contact:{
en:{kicker:"Contact",title:"Research, institutions, culture.",deck:"VOCE welcomes serious exchanges with researchers, institutions, foundations, cultural organisations and practitioners working on the systems it studies.",meta:["Paris","London","Dubai","China"],sections:[
["01","VOCE Association","Registered office: 94 rue Montmartre, 75002 Paris, France.","Email: contact@voce.life","LinkedIn: VOCE Association"],
["02","Research & expertise","For research dialogue, scientific committee exchanges, source corrections or expert contribution, contact VOCE with the subject area and the nature of the contribution.","VOCE prioritises exchanges that add evidence, challenge a mechanism or provide direct knowledge of an ecosystem."],
["03","Institutional & cultural work","VOCE can engage with institutions, foundations and cultural organisations around research, seminars, scientific and cultural mediation, AI governance, digital environments and the human consequences of technological change.","The approach remains research-led rather than promotional."]
],linksTitle:"Start from a VOCE pathway",links:[["About VOCE","Understand the institution first.","/about"],["Research","Current agenda and methods.","/research"],["Governance & Standards","Method, evidence and independence.","/standards"],["LinkedIn","Follow current editorial work.","https://fr.linkedin.com/in/voce-association-0030763b6"]]},
fr:{kicker:"Contact",title:"Recherche, institutions, culture.",deck:"VOCE accueille les échanges sérieux avec chercheurs, institutions, fondations, organisations culturelles et praticiens travaillant sur les systèmes qu’elle étudie.",meta:["Paris","Londres","Dubaï","Chine"],sections:[
["01","VOCE Association","Siège social: 94 rue Montmartre, 75002 Paris, France.","Email: contact@voce.life","LinkedIn: VOCE Association"],
["02","Recherche & expertise","Pour un échange de recherche, une contribution au comité scientifique, une correction de source ou un apport expert, contacter VOCE en précisant le domaine et la nature de la contribution.","VOCE privilégie les échanges qui ajoutent une preuve, contestent utilement un mécanisme ou apportent une connaissance directe d’un écosystème."],
["03","Travail institutionnel & culturel","VOCE peut travailler avec institutions, fondations et organisations culturelles autour de la recherche, des séminaires, de la médiation scientifique et culturelle, de la gouvernance de l’IA, des environnements numériques et des conséquences humaines du changement technologique.","L’approche reste guidée par la recherche plutôt que par la promotion."]
],linksTitle:"Entrer dans VOCE",links:[["À propos de VOCE","Comprendre d’abord l’institution.","/about"],["Research","Agenda actuel et méthodes.","/research"],["Gouvernance & standards","Méthode, preuve et indépendance.","/standards"],["LinkedIn","Suivre le travail éditorial actuel.","https://fr.linkedin.com/in/voce-association-0030763b6"]]},
it:{kicker:"Contatti",title:"Ricerca, istituzioni, cultura.",deck:"VOCE accoglie scambi seri con ricercatori, istituzioni, fondazioni, organizzazioni culturali e professionisti che lavorano sui sistemi studiati.",meta:["Parigi","Londra","Dubai","Cina"],sections:[
["01","VOCE Association","Sede legale: 94 rue Montmartre, 75002 Parigi, Francia.","Email: contact@voce.life","LinkedIn: VOCE Association"],
["02","Ricerca & competenza","Per dialogo di ricerca, scambi con il comitato scientifico, correzioni di fonti o contributi esperti, contattare VOCE indicando l’area e la natura del contributo.","VOCE privilegia scambi che aggiungono evidenza, mettono utilmente alla prova un meccanismo o portano conoscenza diretta di un ecosistema."],
["03","Lavoro istituzionale & culturale","VOCE può lavorare con istituzioni, fondazioni e organizzazioni culturali su ricerca, seminari, mediazione scientifica e culturale, governance dell’IA, ambienti digitali e conseguenze umane del cambiamento tecnologico.","L’approccio resta guidato dalla ricerca e non dalla promozione."]
],linksTitle:"Entrare in VOCE",links:[["Chi è VOCE","Comprendere prima l’istituzione.","/about"],["Research","Agenda attuale e metodi.","/research"],["Governance & standard","Metodo, evidenza e indipendenza.","/standards"],["LinkedIn","Segui il lavoro editoriale attuale.","https://fr.linkedin.com/in/voce-association-0030763b6"]]}
}
};
const COMMON={
en:{navThemes:"Themes",navResearch:"Research",navAcademy:"Academy",navStandards:"Standards",navPublications:"Publications",navArt:"Art",navAbout:"About",links:"Continue",institution:"Institution",work:"Work",contact:"Contact",home:"Home",linkedin:"LinkedIn",sideAbout:"About",sideResearch:"Research",sideStandards:"Governance & Standards",sidePublications:"Publications",sideContact:"Contact",legal:"Legal",privacy:"Privacy"},
fr:{navThemes:"Thèmes",navResearch:"Recherche",navAcademy:"Academy",navStandards:"Normes",navPublications:"Publications",navArt:"Art",navAbout:"À propos",links:"Poursuivre",institution:"Institution",work:"Travaux",contact:"Contact",home:"Accueil",linkedin:"LinkedIn",sideAbout:"À propos",sideResearch:"Recherche",sideStandards:"Gouvernance & standards",sidePublications:"Publications",sideContact:"Contact",legal:"Mentions légales",privacy:"Confidentialité"},
it:{navThemes:"Temi",navResearch:"Ricerca",navAcademy:"Academy",navStandards:"Standard",navPublications:"Pubblicazioni",navArt:"Art",navAbout:"Chi siamo",links:"Continua",institution:"Istituzione",work:"Lavoro",contact:"Contatti",home:"Home",linkedin:"LinkedIn",sideAbout:"Chi siamo",sideResearch:"Ricerca",sideStandards:"Governance & standard",sidePublications:"Pubblicazioni",sideContact:"Contatti",legal:"Note legali",privacy:"Privacy"}
};
function currentLang(){return localStorage.getItem("voce-lang")||"en"}
function renderInstitution(l){
 const p=PAGES[window.VOCE_PAGE][l]||PAGES[window.VOCE_PAGE].en;
 const c=COMMON[l]||COMMON.en;
 document.documentElement.lang=l;
 document.title=p.title+" — VOCE";
 document.querySelectorAll("[data-lang]").forEach(b=>{b.classList.toggle("active",b.dataset.lang===l);b.setAttribute("aria-pressed",b.dataset.lang===l?"true":"false")});
 if(document.querySelector("[data-nav-themes]")) document.querySelector("[data-nav-themes]").textContent=c.navThemes;
 if(document.querySelector("[data-nav-research]")) document.querySelector("[data-nav-research]").textContent=c.navResearch;
 if(document.querySelector("[data-nav-academy]")) document.querySelector("[data-nav-academy]").textContent=c.navAcademy;
 if(document.querySelector("[data-nav-standards]")) document.querySelector("[data-nav-standards]").textContent=c.navStandards;
 if(document.querySelector("[data-nav-publications]")) document.querySelector("[data-nav-publications]").textContent=c.navPublications;
 if(document.querySelector("[data-nav-art]")) document.querySelector("[data-nav-art]").textContent=c.navArt;
 if(document.querySelector("[data-nav-about]")) document.querySelector("[data-nav-about]").textContent=c.navAbout;
 document.querySelector("#page-kicker").textContent=p.kicker;
 document.querySelector("#page-title").textContent=p.title;
 document.querySelector("#page-deck").textContent=p.deck;
 document.querySelector("#page-meta").innerHTML=p.meta.map(x=>'<span>'+x+'</span>').join("");
 const sections=document.querySelector("#sections");
 sections.innerHTML=p.sections.map(s=>'<section class="chapter"><div class="chapter-no">'+s[0]+'</div><h2>'+s[1]+'</h2>'+s.slice(2).map((x,i)=>'<p'+(i===0&&s.length>4?' class="signal"':'')+'>'+x+'</p>').join("")+'</section>').join("");
 document.querySelector("#links-title").textContent=p.linksTitle;
 document.querySelector("#links").innerHTML=p.links.map(x=>'<a class="link-row" href="'+x[2]+'"'+(x[2].startsWith("http")?' target="_blank" rel="noopener"':'')+'><div class="label">'+c.links+'</div><div><h3>'+x[0]+'</h3><p>'+x[1]+'</p></div><div class="go">'+(l==="fr"?"Ouvrir":l==="it"?"Apri":"Open")+'</div></a>').join("");
 document.querySelector("#f-inst").textContent=c.institution;
 document.querySelector("#f-work").textContent=c.work;
 document.querySelector("#f-about").textContent=c.navAbout;
 document.querySelector("#f-standards").textContent=c.navStandards;
 document.querySelector("#f-contact").textContent=c.contact;
 document.querySelector("#f-research").textContent=c.navResearch;
 document.querySelector("#f-ai").textContent=l==="fr"?"Gouvernance de l’IA":l==="it"?"Governance dell’IA":"AI Governance";
 document.querySelector("#f-pubs").textContent=c.navPublications;
 document.querySelector("#side-about").textContent=c.sideAbout;
 document.querySelector("#side-research").textContent=c.sideResearch;
 document.querySelector("#side-standards").textContent=c.sideStandards;
 document.querySelector("#side-publications").textContent=c.sidePublications;
 document.querySelector("#side-contact").textContent=c.sideContact;
 if(document.querySelector("#f-legal")) document.querySelector("#f-legal").textContent=c.legal;
 if(document.querySelector("#f-privacy")) document.querySelector("#f-privacy").textContent=c.privacy;
}
function setLang(l){localStorage.setItem("voce-lang",l);renderInstitution(l)}
document.addEventListener("DOMContentLoaded",()=>{
 document.querySelectorAll("[data-lang]").forEach(b=>b.addEventListener("click",()=>setLang(b.dataset.lang)));
 renderInstitution(currentLang());
});